export const movie = [
  {
    title: "Scarface",
    year: "1983",
    genre: "Action",
    type: "movie",
    director: "Brian De Palma",
    maincast: "Al Pacino",
    img: "https://m.media-amazon.com/images/M/MV5BNjdjNGQ4NDEtNTEwYS00MTgxLTliYzQtYzE2ZDRiZjFhZmNlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BYTBjNDBhZWUtZjg1MS00NzhjLWJlNWUtM2E0ZjcwZGExYzY3XkEyXkFqcGdeQXVyMjMzMDI4MjQ@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: false,
    link: "cv276Wg3e7I",
  },
  {
    title: "Breaking Bad",
    year: "2008",
    genre: "Drama",
    type: "tv",
    director: "Vince Gilligan",
    maincast: "Bryan Cranston,Anna Gunn,Aaron Paul",
    img: "https://m.media-amazon.com/images/M/MV5BYTU3NWI5OGMtZmZhNy00MjVmLTk1YzAtZjA3ZDA3NzcyNDUxXkEyXkFqcGdeQXVyODY5Njk4Njc@._V1_FMjpg_UX1000_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BMTJiMzgwZTktYzZhZC00YzhhLWEzZDUtMGM2NTE4MzQ4NGFmXkEyXkFqcGdeQWpybA@@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: false,
    link: "HhesaQXLuRY",
  },
  {
    title: "Avatar: The Way of Water",
    year: "2022",
    genre: "Sci-fi",
    type: "movie",
    director: "James Cameron",
    maincast: "Sam Worthington,Zoe Saldana",
    img: "https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_FMjpg_UX1000_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BNzQyOTJjOTEtOTFiYi00NzgyLWFiYmUtYTMzYzk5ODYwMjc2XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: true,
    link: "d9MyW72ELq0",
  },
  {
    title: "Avatar",
    year: "2009",
    genre: "Sci-fi",
    type: "movie",
    director: "James Cameron",
    maincast: "Sam Worthington,Zoe Saldana",
    img: "https://m.media-amazon.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BMTMxOTEwNDcxN15BMl5BanBnXkFtZTcwOTg0MTUzNA@@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "5PSNL1qE6VY",
  },
  {
    title: "Spiderman",
    year: "2002",
    genre: "Action",
    type: "movie",
    director: "Sam Raimi",
    maincast: "Tobey Maguire,Kirsten Dunst",
    img: "https://m.media-amazon.com/images/M/MV5BZDEyN2NhMjgtMjdhNi00MmNlLWE5YTgtZGE4MzNjMTRlMGEwXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_.jpg",
    banner:
      "https://occ-0-32-988.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABZrkp8RvUrZVjc9GYn8-jlxnEa66xgTexL7oinRF0s2MtkbCV5CsuuRlR48sqMP0twyY46ToqL__Y3uflZ_Ln0DgZrqy6cfKas87.jpg?r=f3d",

    rating: 4,
    isFeatured: true,
    isTrending: false,
    link: "TYMMOjBUPMM",
  },
  {
    title: "The Matrix",
    year: "1999",
    genre: "Sci-fi",
    type: "movie",
    director: "Lana Wachowski,Lilly Wachowski",
    maincast: "Keanu Reaves",
    img: "https://m.media-amazon.com/images/M/MV5BZGMzZDc3ZGUtMDIzYy00Y2ViLWE3ZGYtNDg2ZWM0YjBiMTk2XkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "nUEQNVV3Gfs",
  },
  {
    title: "Black Panther:Wakanda Forever",
    year: "2022",
    genre: "Sci-fi",
    type: "movie",
    director: "Ryan Coogler",
    maincast: "Letitia Wright",
    img: "https://m.media-amazon.com/images/M/MV5BNTM4NjIxNmEtYWE5NS00NDczLTkyNWQtYThhNmQyZGQzMjM0XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: true,
    link: "_Z3QKkl1WyM",
  },
  {
    title: "The Godfather",
    year: "1972",
    genre: "Action",
    type: "movie",
    director: "Francis Ford Coppola",
    maincast: "Marlon Brando",
    img: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "UaVTIH8mujA",
  },
  {
    title: "Iron Man",
    year: "2008",
    genre: "Action",
    type: "movie",
    director: "Jon Favreau",
    maincast: "Robert Downey Jr,Gwyneth Paltrow,Terrence Howard",
    img: "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_FMjpg_UX1000_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "8ugaeA-nMTc",
  },
  {
    title: "SPIDER-MAN: NO WAY HOME",
    year: "2021",
    genre: "Sci-fi",
    type: "movie",
    director: "Jon Watts",
    maincast: "Tom Holland,Zendaya",
    img: "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UX1000_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "rt-2cxAiPJk",
  },
  {
    title: "VENOM",
    year: "2018",
    genre: "Sci-fi",
    type: "movie",
    director: "Ruben Fleischer",
    maincast: "Tom Hardy",
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTvGNXRmC76GfZrgM7P_oY0nZqg00bsjC7E5zu4dZBReXiHD_kt",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "u9Mv98Gr5pY",
  },
  {
    title: "POKÉMON Detective Pikachu",
    year: "2019",
    genre: "Sci-fi",
    type: "movie",
    director: "Rob Letterman",
    maincast: "Ryan Reynolds",
    img: "https://m.media-amazon.com/images/M/MV5BMDkxNzRmNDYtMDY0OS00N2JhLTkzZWUtMWE3MzZkNDk1MmJiXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_FMjpg_UX1000_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "1roy4o4tqQM",
  },
  {
    title: "IT",
    year: "2017",
    genre: "Horror",
    type: "movie",
    director: "Andy Muschietti",
    maincast: "	Jaeden Lieberher",
    img: "https://upload.wikimedia.org/wikipedia/en/5/5a/It_%282017%29_poster.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "FnCdOQsX5kc",
  },
  {
    title: "Toy Story 4",
    year: "2019",
    genre: "Animated",
    type: "movie",
    director: "Josh Cooley",
    maincast: "Tom Hanks",
    img: "https://upload.wikimedia.org/wikipedia/en/4/4c/Toy_Story_4_poster.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: true,
    link: "wmiIUN-7qhE",
  },
  {
    title: "The Nun",
    year: "2018",
    genre: "Horror",
    type: "movie",
    director: "Corin Hardy",
    maincast: "Bonnie Aarons,Charlotte Hope",
    img: "https://m.media-amazon.com/images/M/MV5BMjM3NzQ5NDcxOF5BMl5BanBnXkFtZTgwNzM4MTQ5NTM@._V1_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "KukngjCoN-s",
  },
  {
    title: "IT CHAPTER TWO",
    year: "2019",
    genre: "Horror",
    type: "movie",
    director: "Andrés Muschietti",
    maincast: "Jessica Chastain",
    img: "https://m.media-amazon.com/images/M/MV5BYTJlNjlkZTktNjEwOS00NzI5LTlkNDAtZmEwZDFmYmM2MjU2XkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_.jpg",
    rating: 3,
    isFeatured: false,
    isTrending: false,
    link: "zqUopiAYdRg",
  },
  {
    title: "Avengers: Infinity War",
    year: "2017",
    genre: "Sci-fi",
    type: "movie",
    director: "Anthony and Joe Russo",
    maincast:
      "Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo,Chris Evans,Scarlett Johansson",
    img: "https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "6ZfuNTqbHE8",
  },
  {
    title: "Incredibles 2",
    year: "2018",
    genre: "Animated",
    type: "movie",
    director: "Brad Bird",
    maincast: "Craig T. Nelson",
    img: "https://upload.wikimedia.org/wikipedia/en/1/1f/Incredibles_2_%282018_animated_film%29.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "i5qOzqD9Rms",
  },
  {
    title: "Speed",
    year: "1994",
    genre: "Action",
    type: "movie",
    director: "Jan de Bont",
    maincast: "Keanu Reeves,Dennis Hopper,Sandra Bullock",
    img: "https://upload.wikimedia.org/wikipedia/en/4/45/Speed_movie_poster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "8piqd2BWeGI",
  },
  {
    title: "Aliens",
    year: "1986",
    genre: "Sci-fi",
    type: "movie",
    director: "James Cameron",
    maincast: " Sigourney Weaver, Michael Biehn, Carrie Henn",
    img: "https://upload.wikimedia.org/wikipedia/en/f/fb/Aliens_poster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "oSeQQlaCZgU",
  },
  {
    title: "Die Hard",
    year: "1988",
    genre: "Action",
    type: "movie",
    director: "John McTiernan",
    maincast: "Bruce Willis,Bonnie Bedelia,Reginald Veljohnson",
    img: "https://m.media-amazon.com/images/M/MV5BZjRlNDUxZjAtOGQ4OC00OTNlLTgxNmQtYTBmMDgwZmNmNjkxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "jaJuwKCmJbY",
  },
  {
    title: "Predator",
    year: "1987",
    genre: "Sci-fi",
    type: "movie",
    director: "John McTiernan",
    maincast: "Arnold Schwarzenegger",
    img: "https://m.media-amazon.com/images/M/MV5BY2QwYmFmZTEtNzY2Mi00ZWMyLWEwY2YtMGIyNGZjMWExOWEyXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "mGLXbK2XWMY",
  },

  {
    title: "John Wick",
    year: "2014",
    genre: "Action",
    type: "movie",
    director: "Chad Stahelski",
    maincast: "Keanu Reeves",
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/9/98/John_Wick_TeaserPoster.jpg/220px-John_Wick_TeaserPoster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "C0BMx-qxsP4",
  },
  {
    title: "Mad Max 2",
    year: "1981",
    genre: "Action",
    type: "movie",
    director: "George Miller",
    maincast: "Mel Gibson",
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/Mad_max_two_the_road_warrior.jpg/220px-Mad_max_two_the_road_warrior.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "UlwtiOyaoo0",
  },
  {
    title: "Inception",
    year: "2010",
    genre: "Sci-fi",
    type: "movie",
    director: "Christopher Nolan",
    maincast: "Leonardo DiCaprio",
    img: "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "YoHD9XEInc0",
  },
  {
    title: "Logan",
    year: "2017",
    genre: "Sci-fi",
    type: "movie",
    director: "James Mangold",
    maincast: "Hugh Jackman, Patrick Stewart",
    img: "https://upload.wikimedia.org/wikipedia/en/3/37/Logan_2017_poster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "Div0iP65aZo",
  },
  {
    title: "Mission: Impossible - Fallout",
    year: "2018",
    genre: "Action",
    type: "movie",
    director: "Christopher McQuarrie",
    maincast: "Tom Cruise",
    img: "https://upload.wikimedia.org/wikipedia/en/f/ff/MI_%E2%80%93_Fallout.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "wb49-oV0F78",
  },
  {
    title: "Baby Driver",
    year: "2017",
    genre: "Action",
    type: "movie",
    director: "Edgar Wright",
    maincast: "Ansel Elgort",
    img: "https://upload.wikimedia.org/wikipedia/en/8/8e/Baby_Driver_poster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "z2z857RSfhk",
  },
  {
    title: "Fast Five",
    year: "2011",
    genre: "Action",
    type: "movie",
    director: "Justin Lin",
    maincast: "Vin Diesel,Paul Walker",
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Fast_Five_poster.jpg/220px-Fast_Five_poster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "vcn2GOuZCKI",
  },
];

// {
//     title: "",
//     year: "",
//     genre: "",
//     type: "movie",
//     director: "",
//     maincast: "",
//     img: "",
//     rating: 4,
//     isFeatured: false,
//     isTrending: false,
//     link: "",
//   },
