export const movie = [
  {
    title: "Scarface",
    year: "1983",
    genre: "Action",
    type: "movie",
    director: "Brian De Palma",
    maincast: "Al Pacino",
    img: "https://m.media-amazon.com/images/M/MV5BNjdjNGQ4NDEtNTEwYS00MTgxLTliYzQtYzE2ZDRiZjFhZmNlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BYTBjNDBhZWUtZjg1MS00NzhjLWJlNWUtM2E0ZjcwZGExYzY3XkEyXkFqcGdeQXVyMjMzMDI4MjQ@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "cv276Wg3e7I",
  },
  {
    title: "Breaking Bad",
    year: "2008",
    genre: "Drama",
    type: "tv",
    director: "Vince Gilligan",
    maincast: "Bryan Cranston,Anna Gunn,Aaron Paul",
    img: "https://m.media-amazon.com/images/M/MV5BYTU3NWI5OGMtZmZhNy00MjVmLTk1YzAtZjA3ZDA3NzcyNDUxXkEyXkFqcGdeQXVyODY5Njk4Njc@._V1_FMjpg_UX1000_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BMTJiMzgwZTktYzZhZC00YzhhLWEzZDUtMGM2NTE4MzQ4NGFmXkEyXkFqcGdeQWpybA@@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "HhesaQXLuRY",
  },
  {
    title: "Avatar: The Way of Water",
    year: "2022",
    genre: "Sci-fi",
    type: "movie",
    director: "James Cameron",
    maincast: "Sam Worthington,Zoe Saldana",
    img: "https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_FMjpg_UX1000_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BNzQyOTJjOTEtOTFiYi00NzgyLWFiYmUtYTMzYzk5ODYwMjc2XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: true,
    link: "d9MyW72ELq0",
  },
  {
    title: "Avatar",
    year: "2009",
    genre: "Sci-fi",
    type: "movie",
    director: "James Cameron",
    maincast: "Sam Worthington,Zoe Saldana",
    img: "https://m.media-amazon.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BMTMxOTEwNDcxN15BMl5BanBnXkFtZTcwOTg0MTUzNA@@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "5PSNL1qE6VY",
  },
  {
    title: "Spiderman",
    year: "2002",
    genre: "Action",
    type: "movie",
    director: "Sam Raimi",
    maincast: "Tobey Maguire,Kirsten Dunst",
    img: "https://m.media-amazon.com/images/M/MV5BZDEyN2NhMjgtMjdhNi00MmNlLWE5YTgtZGE4MzNjMTRlMGEwXkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_.jpg",
    banner:
      "https://occ-0-32-988.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABZrkp8RvUrZVjc9GYn8-jlxnEa66xgTexL7oinRF0s2MtkbCV5CsuuRlR48sqMP0twyY46ToqL__Y3uflZ_Ln0DgZrqy6cfKas87.jpg?r=f3d",

    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "TYMMOjBUPMM",
  },
  {
    title: "The Matrix",
    year: "1999",
    genre: "Sci-fi",
    type: "movie",
    director: "Lana Wachowski,Lilly Wachowski",
    maincast: "Keanu Reaves",
    img: "https://m.media-amazon.com/images/M/MV5BZGMzZDc3ZGUtMDIzYy00Y2ViLWE3ZGYtNDg2ZWM0YjBiMTk2XkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "nUEQNVV3Gfs",
  },
  {
    title: "Black Panther:Wakanda Forever",
    year: "2022",
    genre: "Sci-fi",
    type: "movie",
    director: "Ryan Coogler",
    maincast: "Letitia Wright",
    img: "https://m.media-amazon.com/images/M/MV5BNTM4NjIxNmEtYWE5NS00NDczLTkyNWQtYThhNmQyZGQzMjM0XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: true,
    link: "_Z3QKkl1WyM",
  },
  {
    title: "The Godfather",
    year: "1972",
    genre: "Action",
    type: "movie",
    director: "Francis Ford Coppola",
    maincast: "Marlon Brando",
    img: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "UaVTIH8mujA",
  },
  {
    title: "Iron Man",
    year: "2008",
    genre: "Action",
    type: "movie",
    director: "Jon Favreau",
    maincast: "Robert Downey Jr,Gwyneth Paltrow,Terrence Howard",
    img: "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_FMjpg_UX1000_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "8ugaeA-nMTc",
  },
  {
    title: "SPIDER-MAN: NO WAY HOME",
    year: "2021",
    genre: "Sci-fi",
    type: "movie",
    director: "Jon Watts",
    maincast: "Tom Holland,Zendaya",
    img: "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UX1000_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "rt-2cxAiPJk",
  },
  {
    title: "VENOM",
    year: "2018",
    genre: "Sci-fi",
    type: "movie",
    director: "Ruben Fleischer",
    maincast: "Tom Hardy",
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTvGNXRmC76GfZrgM7P_oY0nZqg00bsjC7E5zu4dZBReXiHD_kt",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "u9Mv98Gr5pY",
  },
  {
    title: "POKÉMON Detective Pikachu",
    year: "2019",
    genre: "Sci-fi",
    type: "movie",
    director: "Rob Letterman",
    maincast: "Ryan Reynolds",
    img: "https://m.media-amazon.com/images/M/MV5BMDkxNzRmNDYtMDY0OS00N2JhLTkzZWUtMWE3MzZkNDk1MmJiXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_FMjpg_UX1000_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "1roy4o4tqQM",
  },
  {
    title: "IT",
    year: "2017",
    genre: "Horror",
    type: "movie",
    director: "Andy Muschietti",
    maincast: "	Jaeden Lieberher",
    img: "https://upload.wikimedia.org/wikipedia/en/5/5a/It_%282017%29_poster.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "FnCdOQsX5kc",
  },
  {
    title: "Toy Story 4",
    year: "2019",
    genre: "Animated",
    type: "movie",
    director: "Josh Cooley",
    maincast: "Tom Hanks",
    img: "https://upload.wikimedia.org/wikipedia/en/4/4c/Toy_Story_4_poster.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: true,
    link: "wmiIUN-7qhE",
  },
  {
    title: "The Nun",
    year: "2018",
    genre: "Horror",
    type: "movie",
    director: "Corin Hardy",
    maincast: "Bonnie Aarons,Charlotte Hope",
    img: "https://m.media-amazon.com/images/M/MV5BMjM3NzQ5NDcxOF5BMl5BanBnXkFtZTgwNzM4MTQ5NTM@._V1_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "KukngjCoN-s",
  },
  {
    title: "IT CHAPTER TWO",
    year: "2019",
    genre: "Horror",
    type: "movie",
    director: "Andrés Muschietti",
    maincast: "Jessica Chastain",
    img: "https://m.media-amazon.com/images/M/MV5BYTJlNjlkZTktNjEwOS00NzI5LTlkNDAtZmEwZDFmYmM2MjU2XkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_.jpg",
    rating: 3,
    isFeatured: false,
    isTrending: false,
    link: "zqUopiAYdRg",
  },
  {
    title: "Avengers: Infinity War",
    year: "2017",
    genre: "Sci-fi",
    type: "movie",
    director: "Anthony and Joe Russo",
    maincast:
      "Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo,Chris Evans,Scarlett Johansson",
    img: "https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "6ZfuNTqbHE8",
  },
  {
    title: "Incredibles 2",
    year: "2018",
    genre: "Animated",
    type: "movie",
    director: "Brad Bird",
    maincast: "Craig T. Nelson",
    img: "https://upload.wikimedia.org/wikipedia/en/1/1f/Incredibles_2_%282018_animated_film%29.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "i5qOzqD9Rms",
  },
  {
    title: "Speed",
    year: "1994",
    genre: "Action",
    type: "movie",
    director: "Jan de Bont",
    maincast: "Keanu Reeves,Dennis Hopper,Sandra Bullock",
    img: "https://upload.wikimedia.org/wikipedia/en/4/45/Speed_movie_poster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "8piqd2BWeGI",
  },
  {
    title: "Aliens",
    year: "1986",
    genre: "Sci-fi",
    type: "movie",
    director: "James Cameron",
    maincast: " Sigourney Weaver, Michael Biehn, Carrie Henn",
    img: "https://upload.wikimedia.org/wikipedia/en/f/fb/Aliens_poster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "oSeQQlaCZgU",
  },
  {
    title: "Die Hard",
    year: "1988",
    genre: "Action",
    type: "movie",
    director: "John McTiernan",
    maincast: "Bruce Willis,Bonnie Bedelia,Reginald Veljohnson",
    img: "https://m.media-amazon.com/images/M/MV5BZjRlNDUxZjAtOGQ4OC00OTNlLTgxNmQtYTBmMDgwZmNmNjkxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "jaJuwKCmJbY",
  },
  {
    title: "Predator",
    year: "1987",
    genre: "Sci-fi",
    type: "movie",
    director: "John McTiernan",
    maincast: "Arnold Schwarzenegger",
    img: "https://m.media-amazon.com/images/M/MV5BY2QwYmFmZTEtNzY2Mi00ZWMyLWEwY2YtMGIyNGZjMWExOWEyXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "mGLXbK2XWMY",
  },

  {
    title: "John Wick",
    year: "2014",
    genre: "Action",
    type: "movie",
    director: "Chad Stahelski",
    maincast: "Keanu Reeves",
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/9/98/John_Wick_TeaserPoster.jpg/220px-John_Wick_TeaserPoster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "C0BMx-qxsP4",
  },
  {
    title: "Mad Max 2",
    year: "1981",
    genre: "Action",
    type: "movie",
    director: "George Miller",
    maincast: "Mel Gibson",
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/Mad_max_two_the_road_warrior.jpg/220px-Mad_max_two_the_road_warrior.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "UlwtiOyaoo0",
  },
  {
    title: "Inception",
    year: "2010",
    genre: "Sci-fi",
    type: "movie",
    director: "Christopher Nolan",
    maincast: "Leonardo DiCaprio",
    img: "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "YoHD9XEInc0",
  },
  {
    title: "Logan",
    year: "2017",
    genre: "Sci-fi",
    type: "movie",
    director: "James Mangold",
    maincast: "Hugh Jackman, Patrick Stewart",
    img: "https://upload.wikimedia.org/wikipedia/en/3/37/Logan_2017_poster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "Div0iP65aZo",
  },
  {
    title: "Mission: Impossible - Fallout",
    year: "2018",
    genre: "Action",
    type: "movie",
    director: "Christopher McQuarrie",
    maincast: "Tom Cruise",
    img: "https://upload.wikimedia.org/wikipedia/en/f/ff/MI_%E2%80%93_Fallout.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "wb49-oV0F78",
  },
  {
    title: "Baby Driver",
    year: "2017",
    genre: "Action",
    type: "movie",
    director: "Edgar Wright",
    maincast: "Ansel Elgort",
    img: "https://upload.wikimedia.org/wikipedia/en/8/8e/Baby_Driver_poster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "z2z857RSfhk",
  },
  {
    title: "Fast Five",
    year: "2011",
    genre: "Action",
    type: "movie",
    director: "Justin Lin",
    maincast: "Vin Diesel,Paul Walker",
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Fast_Five_poster.jpg/220px-Fast_Five_poster.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "vcn2GOuZCKI",
  },
  // NEW MOVIES AND TV SHOWS
  {
    title: "Oppenheimer",
    year: "2023",
    genre: "Drama",
    type: "movie",
    director: "Christopher Nolan",
    maincast: "Cillian Murphy, Emily Blunt, Robert Downey Jr.",
    img: "https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: true,
    link: "uYPbbksJxIg",
  },
  {
    title: "Barbie",
    year: "2023",
    genre: "Comedy",
    type: "movie",
    director: "Greta Gerwig",
    maincast: "Margot Robbie, Ryan Gosling",
    img: "https://m.media-amazon.com/images/M/MV5BNjU3N2QxNzYtMjk1NC00MTc4LTk1NTQtMmUxNTljM2I0NDA5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: true,
    link: "pBk4NYhWNMM",
  },
  {
    title: "Dune: Part Two",
    year: "2024",
    genre: "Sci-fi",
    type: "movie",
    director: "Denis Villeneuve",
    maincast: "Timothée Chalamet, Zendaya, Austin Butler",
    img: "https://m.media-amazon.com/images/M/MV5BN2QyZGU4ZDctOWMzMy00NTc5LThlOGQtODhmNDI1NmY5YzAwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BN2QyZGU4ZDctOWMzMy00NTc5LThlOGQtODhmNDI1NmY5YzAwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: true,
    link: "Way9Dexny3w",
  },
  {
    title: "The Batman",
    year: "2022",
    genre: "Action",
    type: "movie",
    director: "Matt Reeves",
    maincast: "Robert Pattinson, Zoë Kravitz, Paul Dano",
    img: "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: true,
    link: "mqqft2x_Aa4",
  },
  {
    title: "Top Gun: Maverick",
    year: "2022",
    genre: "Action",
    type: "movie",
    director: "Joseph Kosinski",
    maincast: "Tom Cruise, Miles Teller, Jennifer Connelly",
    img: "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "giXco2jaZ_4",
  },
  {
    title: "Everything Everywhere All at Once",
    year: "2022",
    genre: "Sci-fi",
    type: "movie",
    director: "Daniel Kwan, Daniel Scheinert",
    maincast: "Michelle Yeoh, Stephanie Hsu, Ke Huy Quan",
    img: "https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "wxN1T1uxQ2g",
  },
  {
    title: "Stranger Things",
    year: "2016",
    genre: "Sci-fi",
    type: "tv",
    director: "The Duffer Brothers",
    maincast: "Millie Bobby Brown, Finn Wolfhard, David Harbour",
    img: "https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzZWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzZWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: true,
    link: "b9EkMc79ZSU",
  },
  {
    title: "The Witcher",
    year: "2019",
    genre: "Action",
    type: "tv",
    director: "Lauren Schmidt Hissrich",
    maincast: "Henry Cavill, Freya Allan, Anya Chalotra",
    img: "https://m.media-amazon.com/images/M/MV5BN2FiOWU4YzYtMzZiOS00MzcyLTlkOGEtOTgwZmEwMzAxMzA3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "ndl1W4ltcmg",
  },
  {
    title: "The Last of Us",
    year: "2023",
    genre: "Drama",
    type: "tv",
    director: "Craig Mazin, Neil Druckmann",
    maincast: "Pedro Pascal, Bella Ramsey",
    img: "https://m.media-amazon.com/images/M/MV5BZGUzYTI3M2EtZmM0Yy00NGUyLWI4ODEtN2Q3ZGJlYzhhZjU3XkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BZGUzYTI3M2EtZmM0Yy00NGUyLWI4ODEtN2Q3ZGJlYzhhZjU3XkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: true,
    link: "uLtkt8BonwM",
  },
  {
    title: "Wednesday",
    year: "2022",
    genre: "Comedy",
    type: "tv",
    director: "Tim Burton",
    maincast: "Jenna Ortega, Gwendoline Christie",
    img: "https://m.media-amazon.com/images/M/MV5BM2ZmMjEyZmYtOGM4YS00YTNhLWE3ZDMtNzQxM2RhNjBlODIyXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "Di310WS8zLk",
  },
  {
    title: "House of the Dragon",
    year: "2022",
    genre: "Drama",
    type: "tv",
    director: "Ryan Condal, George R.R. Martin",
    maincast: "Matt Smith, Emma D'Arcy, Olivia Cooke",
    img: "https://m.media-amazon.com/images/M/MV5BZjBiOGIyY2YtOTA3OC00YzY1LThkYjktMGRkYTNhNTExY2I2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "DotnJ7tTA34",
  },
  {
    title: "Guardians of the Galaxy Vol. 3",
    year: "2023",
    genre: "Sci-fi",
    type: "movie",
    director: "James Gunn",
    maincast: "Chris Pratt, Zoe Saldaña, Dave Bautista",
    img: "https://m.media-amazon.com/images/M/MV5BMDgxOTdjMzYtZGQxMS00ZTAzLWI4Y2UtMTQzN2VlYjYyZWRiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "u3V5KDHRQvk",
  },
  {
    title: "John Wick: Chapter 4",
    year: "2023",
    genre: "Action",
    type: "movie",
    director: "Chad Stahelski",
    maincast: "Keanu Reeves, Donnie Yen, Bill Skarsgård",
    img: "https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "qEVUtrk8_B4",
  },
  {
    title: "Killers of the Flower Moon",
    year: "2023",
    genre: "Drama",
    type: "movie",
    director: "Martin Scorsese",
    maincast: "Leonardo DiCaprio, Robert De Niro, Lily Gladstone",
    img: "https://m.media-amazon.com/images/M/MV5BMjE4ZTZlNDAtM2Q3YS00YjFhLThjN2ItODc3OWQ3YzY5NDlhXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "EP34Yoxs3FQ",
  },
  {
    title: "Spider-Man: Across the Spider-Verse",
    year: "2023",
    genre: "Animated",
    type: "movie",
    director: "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
    maincast: "Shameik Moore, Hailee Steinfeld, Oscar Isaac",
    img: "https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "cqGjhVJWtEg",
  },
  {
    title: "Elemental",
    year: "2023",
    genre: "Animated",
    type: "movie",
    director: "Peter Sohn",
    maincast: "Leah Lewis, Mamoudou Athie",
    img: "https://m.media-amazon.com/images/M/MV5BMTQ4MjA0MDIzM15BMl5BanBnXkFtZTgwOTgxNzQ2NjM@._V1_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "hXzcyx9V0xw",
  },
  {
    title: "The Super Mario Bros. Movie",
    year: "2023",
    genre: "Animated",
    type: "movie",
    director: "Aaron Horvath, Michael Jelenic",
    maincast: "Chris Pratt, Anya Taylor-Joy, Jack Black",
    img: "https://m.media-amazon.com/images/M/MV5BOTJhNzlmNzctNTU5Yy00N2YwLThhMjQtZDM0YjEzN2Y0ZjNhXkEyXkFqcGdeQXVyMTEwMTQ4MzU5._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "TnGl01FkMMo",
  },
  {
    title: "The Conjuring",
    year: "2013",
    genre: "Horror",
    type: "movie",
    director: "James Wan",
    maincast: "Vera Farmiga, Patrick Wilson",
    img: "https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "k10ETZ41q5o",
  },
  {
    title: "A Quiet Place",
    year: "2018",
    genre: "Horror",
    type: "movie",
    director: "John Krasinski",
    maincast: "Emily Blunt, John Krasinski",
    img: "https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "WR7cc5t7tv8",
  },
  {
    title: "Get Out",
    year: "2017",
    genre: "Horror",
    type: "movie",
    director: "Jordan Peele",
    maincast: "Daniel Kaluuya, Allison Williams",
    img: "https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "DzfpyUB60YY",
  },
  {
    title: "The Hangover",
    year: "2009",
    genre: "Comedy",
    type: "movie",
    director: "Todd Phillips",
    maincast: "Bradley Cooper, Ed Helms, Zach Galifianakis",
    img: "https://m.media-amazon.com/images/M/MV5BNGQwZjg5YmYtY2VkNC00NzliLTljYTctNzI5NmU3MjE2ODQzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "tcdUhdOlz9M",
  },
  {
    title: "Superbad",
    year: "2007",
    genre: "Comedy",
    type: "movie",
    director: "Greg Mottola",
    maincast: "Jonah Hill, Michael Cera, Christopher Mintz-Plasse",
    img: "https://m.media-amazon.com/images/M/MV5BY2VkMDg4ZTYtN2M3Yy00NWZhLWE3MDMtNWFiNDA0NWJhN2Y3XkEyXkFqcGdeQXVyODY5Njk4Njc@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "4eaZ_48ZYog",
  },
  {
    title: "The Grand Budapest Hotel",
    year: "2014",
    genre: "Comedy",
    type: "movie",
    director: "Wes Anderson",
    maincast: "Ralph Fiennes, F. Murray Abraham, Tony Revolori",
    img: "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "1Fg5iWmQjwk",
  },
  {
    title: "Knives Out",
    year: "2019",
    genre: "Comedy",
    type: "movie",
    director: "Rian Johnson",
    maincast: "Daniel Craig, Chris Evans, Ana de Armas",
    img: "https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "qGqiHJTsRkQ",
  },
  {
    title: "Interstellar",
    year: "2014",
    genre: "Sci-fi",
    type: "movie",
    director: "Christopher Nolan",
    maincast: "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
    img: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: true,
    link: "zSWdZVtXT7E",
  },
  {
    title: "Blade Runner 2049",
    year: "2017",
    genre: "Sci-fi",
    type: "movie",
    director: "Denis Villeneuve",
    maincast: "Ryan Gosling, Harrison Ford, Ana de Armas",
    img: "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "gCcx85zbxz4",
  },
  {
    title: "Arrival",
    year: "2016",
    genre: "Sci-fi",
    type: "movie",
    director: "Denis Villeneuve",
    maincast: "Amy Adams, Jeremy Renner, Forest Whitaker",
    img: "https://m.media-amazon.com/images/M/MV5BMTExMzU0ODcxNDheQTJeQWpwZ15BbWU4MDE1OTI4MzAy._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "tFMo3UJ4B4g",
  },
  // ============ BATCH 1: ACTION MOVIES ============
  {
    title: "The Dark Knight",
    year: "2008",
    genre: "Action",
    type: "movie",
    director: "Christopher Nolan",
    maincast: "Christian Bale, Heath Ledger, Aaron Eckhart",
    img: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg",
    banner:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg",
    rating: 5,
    isFeatured: true,
    isTrending: true,
    link: "EXeTwQWrcwY",
  },
  {
    title: "Gladiator",
    year: "2000",
    genre: "Action",
    type: "movie",
    director: "Ridley Scott",
    maincast: "Russell Crowe, Joaquin Phoenix",
    img: "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "owK1qxDselE",
  },
  {
    title: "The Bourne Identity",
    year: "2002",
    genre: "Action",
    type: "movie",
    director: "Doug Liman",
    maincast: "Matt Damon, Franka Potente",
    img: "https://m.media-amazon.com/images/M/MV5BM2JkNGU0ZGMtZjVjNS00NjgyLWEyOWYtZmRmZGQyN2IxZjA2XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "FpKaB5dvQ4g",
  },
  {
    title: "Kill Bill: Vol. 1",
    year: "2003",
    genre: "Action",
    type: "movie",
    director: "Quentin Tarantino",
    maincast: "Uma Thurman, David Carradine",
    img: "https://m.media-amazon.com/images/M/MV5BNzM3NDFhYTAtYmU5Mi00NGRmLTljYjgtMDkyODQ4MjNkMGY2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "7kSuas6mRpk",
  },
  {
    title: "300",
    year: "2006",
    genre: "Action",
    type: "movie",
    director: "Zack Snyder",
    maincast: "Gerard Butler, Lena Headey",
    img: "https://m.media-amazon.com/images/M/MV5BNjMxMjcxMzU5OV5BMl5BanBnXkFtZTgwNzQ0NTU0OTE@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "UrIbxk7idYA",
  },
  {
    title: "The Raid",
    year: "2011",
    genre: "Action",
    type: "movie",
    director: "Gareth Evans",
    maincast: "Iko Uwais, Joe Taslim",
    img: "https://m.media-amazon.com/images/M/MV5BNzM3OGE5NDUtMWE4NC00ODM0LWI3N2EtNThmNDhkYjkxYjM0L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "m6Q7KnXpNOg",
  },
  {
    title: "Lethal Weapon",
    year: "1987",
    genre: "Action",
    type: "movie",
    director: "Richard Donner",
    maincast: "Mel Gibson, Danny Glover",
    img: "https://m.media-amazon.com/images/M/MV5BNDc0ZTQ0MjQtYzJhYi00Yzk3LTkxNjAtYzU4ZDdmNTU0ZWI1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "huT5__BqY_U",
  },
  {
    title: "Rambo: First Blood",
    year: "1982",
    genre: "Action",
    type: "movie",
    director: "Ted Kotcheff",
    maincast: "Sylvester Stallone, Richard Crenna",
    img: "https://m.media-amazon.com/images/M/MV5BOGQwYjg0ZTMtNDBkMC00Y2I2LThjZDctYWZkYjg4MTQ2YzgwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "O5pBN4VMGU8",
  },
  {
    title: "The Terminator",
    year: "1984",
    genre: "Action",
    type: "movie",
    director: "James Cameron",
    maincast: "Arnold Schwarzenegger, Linda Hamilton",
    img: "https://m.media-amazon.com/images/M/MV5BYTViNzMxZjEtZGEwNy00MDNiLWIzNGQtZDY2MjQ1OWViZjFmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "k64P4l2Wmeg",
  },
  {
    title: "Terminator 2: Judgment Day",
    year: "1991",
    genre: "Action",
    type: "movie",
    director: "James Cameron",
    maincast: "Arnold Schwarzenegger, Linda Hamilton, Edward Furlong",
    img: "https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "CRRlbK5w8AE",
  },
  // ============ BATCH 2: MORE ACTION MOVIES ============
  {
    title: "Total Recall",
    year: "1990",
    genre: "Action",
    type: "movie",
    director: "Paul Verhoeven",
    maincast: "Arnold Schwarzenegger, Sharon Stone",
    img: "https://m.media-amazon.com/images/M/MV5BYzU1YmJjMGEtMjY4Yy00MTFlLWE3NTUtNzI3YjkwZTMxZjZmXkEyXkFqcGdeQXVyNDc2NjEyMw@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "WFMLGEHdIjE",
  },
  {
    title: "RoboCop",
    year: "1987",
    genre: "Action",
    type: "movie",
    director: "Paul Verhoeven",
    maincast: "Peter Weller, Nancy Allen",
    img: "https://m.media-amazon.com/images/M/MV5BNzU2YWUzNGMtODlhMi00MjlmLThmOWMtZjIyMTYzNDU3NmY0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "R0V2U3ajfvA",
  },
  {
    title: "Con Air",
    year: "1997",
    genre: "Action",
    type: "movie",
    director: "Simon West",
    maincast: "Nicolas Cage, John Cusack, John Malkovich",
    img: "https://m.media-amazon.com/images/M/MV5BYjE2OTdhOTktNzU1NS00YjRhLTgzMWQtMGFmNDI5YmRhYjg0L2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "H3K8ZNOQRDU",
  },
  {
    title: "The Rock",
    year: "1996",
    genre: "Action",
    type: "movie",
    director: "Michael Bay",
    maincast: "Sean Connery, Nicolas Cage, Ed Harris",
    img: "https://m.media-amazon.com/images/M/MV5BZDJjOTE0N2EtMmRlZS00NzU0LWE0ZWQtM2Q3MWMxNjcwZjBhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "jEgX64n3T7g",
  },
  {
    title: "Face/Off",
    year: "1997",
    genre: "Action",
    type: "movie",
    director: "John Woo",
    maincast: "John Travolta, Nicolas Cage",
    img: "https://m.media-amazon.com/images/M/MV5BNjdjNjljOTItYWI5NC00ZDc4LTk4MDAtNDhkODliZGM5NDRkXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "BIyvSKCnBnk",
  },
  {
    title: "Point Break",
    year: "1991",
    genre: "Action",
    type: "movie",
    director: "Kathryn Bigelow",
    maincast: "Keanu Reeves, Patrick Swayze",
    img: "https://m.media-amazon.com/images/M/MV5BNzhmNGI4ZGUtYTU4NC00OTk0LWE4YmItMzBmNmI4ZDU5N2EzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "j5LLSgoPhX8",
  },
  {
    title: "Heat",
    year: "1995",
    genre: "Action",
    type: "movie",
    director: "Michael Mann",
    maincast: "Al Pacino, Robert De Niro, Val Kilmer",
    img: "https://m.media-amazon.com/images/M/MV5BNGMwNzUwNjYtZWM5NS00YzMyLWI4NjAtNjM0ZDBiMzE1YWExXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "0ssgLzhBoss",
  },
  {
    title: "Casino Royale",
    year: "2006",
    genre: "Action",
    type: "movie",
    director: "Martin Campbell",
    maincast: "Daniel Craig, Eva Green, Mads Mikkelsen",
    img: "https://m.media-amazon.com/images/M/MV5BMDI5ZWJhOWItYTlhOC00YWNhLTlkNzctNDU5YTI1M2E1MWZhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "36mnx8dBbGE",
  },
  {
    title: "Skyfall",
    year: "2012",
    genre: "Action",
    type: "movie",
    director: "Sam Mendes",
    maincast: "Daniel Craig, Javier Bardem, Judi Dench",
    img: "https://m.media-amazon.com/images/M/MV5BMWZiNjE2OWItMTkwNy00ZWQzLWI0NTgtMWE0NjNiYTljN2Q1XkEyXkFqcGdeQXVyNzAwMjYxMzA@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "6kw1UVovByw",
  },
  {
    title: "Taken",
    year: "2008",
    genre: "Action",
    type: "movie",
    director: "Pierre Morel",
    maincast: "Liam Neeson, Maggie Grace",
    img: "https://m.media-amazon.com/images/M/MV5BMTM4NzQ0OTYyOF5BMl5BanBnXkFtZTcwMDkyNjQyMg@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "uPJVJBm9TPA",
  },
  // ============ BATCH 3: SCI-FI MOVIES ============
  {
    title: "E.T. the Extra-Terrestrial",
    year: "1982",
    genre: "Sci-fi",
    type: "movie",
    director: "Steven Spielberg",
    maincast: "Henry Thomas, Drew Barrymore",
    img: "https://m.media-amazon.com/images/M/MV5BMTQ2ODFlMDAtNzdhOC00ZDYzLWE3YTMtNDU1ZGRiZjk3Yjk4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "qYAETtIIClk",
  },
  {
    title: "Close Encounters of the Third Kind",
    year: "1977",
    genre: "Sci-fi",
    type: "movie",
    director: "Steven Spielberg",
    maincast: "Richard Dreyfuss, Teri Garr",
    img: "https://m.media-amazon.com/images/M/MV5BMjE3NjE1NjAyN15BMl5BanBnXkFtZTgwNTI3NzA5MTI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "dSpQ3G1jcxw",
  },
  {
    title: "2001: A Space Odyssey",
    year: "1968",
    genre: "Sci-fi",
    type: "movie",
    director: "Stanley Kubrick",
    maincast: "Keir Dullea, Gary Lockwood",
    img: "https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "oR_e9y-bka0",
  },
  {
    title: "Gravity",
    year: "2013",
    genre: "Sci-fi",
    type: "movie",
    director: "Alfonso Cuarón",
    maincast: "Sandra Bullock, George Clooney",
    img: "https://m.media-amazon.com/images/M/MV5BNjE5MzYwMzYxMF5BMl5BanBnXkFtZTcwOTk4MTk0OQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "OiTiKOy59o4",
  },
  {
    title: "The Martian",
    year: "2015",
    genre: "Sci-fi",
    type: "movie",
    director: "Ridley Scott",
    maincast: "Matt Damon, Jessica Chastain",
    img: "https://m.media-amazon.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "ej3ioOneTy8",
  },
  {
    title: "Ex Machina",
    year: "2014",
    genre: "Sci-fi",
    type: "movie",
    director: "Alex Garland",
    maincast: "Alicia Vikander, Domhnall Gleeson, Oscar Isaac",
    img: "https://m.media-amazon.com/images/M/MV5BMTUxNzc0OTIxMV5BMl5BanBnXkFtZTgwNDI3NzU2NDE@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "EoQuVnKhxaM",
  },
  {
    title: "District 9",
    year: "2009",
    genre: "Sci-fi",
    type: "movie",
    director: "Neill Blomkamp",
    maincast: "Sharlto Copley, Jason Cope",
    img: "https://m.media-amazon.com/images/M/MV5BYzA0OWVhMjEtMTY2NC00NDg3LThkNTgtN2YwMWM3OGM0NzM3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "DyLUwOcR5pk",
  },
  {
    title: "Edge of Tomorrow",
    year: "2014",
    genre: "Sci-fi",
    type: "movie",
    director: "Doug Liman",
    maincast: "Tom Cruise, Emily Blunt",
    img: "https://m.media-amazon.com/images/M/MV5BMTc5OTk4MTM3M15BMl5BanBnXkFtZTgwODcxNjg3MDE@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "vw61gCe2oqI",
  },
  {
    title: "Moon",
    year: "2009",
    genre: "Sci-fi",
    type: "movie",
    director: "Duncan Jones",
    maincast: "Sam Rockwell, Kevin Spacey",
    img: "https://m.media-amazon.com/images/M/MV5BMTgzODgyNTQwOV5BMl5BanBnXkFtZTcwNzc0NTc0Mg@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "twuScTcDP_Q",
  },
  {
    title: "Looper",
    year: "2012",
    genre: "Sci-fi",
    type: "movie",
    director: "Rian Johnson",
    maincast: "Joseph Gordon-Levitt, Bruce Willis, Emily Blunt",
    img: "https://m.media-amazon.com/images/M/MV5BMTg5NTA3NTg4NF5BMl5BanBnXkFtZTcwNTA0NDYzOA@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "2iQuhsmtfHw",
  },
  // ============ BATCH 4: MORE SCI-FI MOVIES ============
  {
    title: "Oblivion",
    year: "2013",
    genre: "Sci-fi",
    type: "movie",
    director: "Joseph Kosinski",
    maincast: "Tom Cruise, Morgan Freeman, Olga Kurylenko",
    img: "https://m.media-amazon.com/images/M/MV5BMTQwMDY0MTA4MF5BMl5BanBnXkFtZTcwNzI3MDgxOQ@@._V1_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "XmIIgE7eSak",
  },
  {
    title: "Pacific Rim",
    year: "2013",
    genre: "Sci-fi",
    type: "movie",
    director: "Guillermo del Toro",
    maincast: "Charlie Hunnam, Idris Elba, Rinko Kikuchi",
    img: "https://m.media-amazon.com/images/M/MV5BMTY3MTI5NjQ4Nl5BMl5BanBnXkFtZTcwOTU1OTU0OQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "5guMumPFBag",
  },
  {
    title: "Annihilation",
    year: "2018",
    genre: "Sci-fi",
    type: "movie",
    director: "Alex Garland",
    maincast: "Natalie Portman, Jennifer Jason Leigh, Tessa Thompson",
    img: "https://m.media-amazon.com/images/M/MV5BMTk2Mjc2NzYxNl5BMl5BanBnXkFtZTgwMTA2OTA1NDM@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "89OP78l9oF0",
  },
  {
    title: "Passengers",
    year: "2016",
    genre: "Sci-fi",
    type: "movie",
    director: "Morten Tyldum",
    maincast: "Jennifer Lawrence, Chris Pratt",
    img: "https://m.media-amazon.com/images/M/MV5BZjY3YzllOTMtOGEyZS00ZDdhLTgyNTAtMTcyNTlhMWE2M2VmXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "7BWWWQzTpNU",
  },
  {
    title: "Minority Report",
    year: "2002",
    genre: "Sci-fi",
    type: "movie",
    director: "Steven Spielberg",
    maincast: "Tom Cruise, Colin Farrell, Samantha Morton",
    img: "https://m.media-amazon.com/images/M/MV5BZTI3YzZkZjMtMGMwNS00MGI2LWExZmMtN2M2YTM0OGQyNDgzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "lG7DGMgfOb8",
  },
  {
    title: "War of the Worlds",
    year: "2005",
    genre: "Sci-fi",
    type: "movie",
    director: "Steven Spielberg",
    maincast: "Tom Cruise, Dakota Fanning, Tim Robbins",
    img: "https://m.media-amazon.com/images/M/MV5BNWEyOGQzMmUtNDkwMC00NWI2LTkxNWMtMDhkMjM0NjdhYTE4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "sPbjPOgRtyA",
  },
  {
    title: "I, Robot",
    year: "2004",
    genre: "Sci-fi",
    type: "movie",
    director: "Alex Proyas",
    maincast: "Will Smith, Bridget Moynahan",
    img: "https://m.media-amazon.com/images/M/MV5BNmE1OWI2ZGItMDUyOS00MmU5LWE0MzItYjY4NjI2Yjc4MzQ0L2ltYWdlXkEyXkFqcGdeQXVyNDIyNjA2MTk@._V1_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "rL6RRIOYmeM",
  },
  {
    title: "Independence Day",
    year: "1996",
    genre: "Sci-fi",
    type: "movie",
    director: "Roland Emmerich",
    maincast: "Will Smith, Bill Pullman, Jeff Goldblum",
    img: "https://m.media-amazon.com/images/M/MV5BMGQwNDNkMmItYWY1Yy00YTZmLWE5OTAtODU0MGZmMzQ1NDdkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "B3NfZihUvMs",
  },
  {
    title: "The Day the Earth Stood Still",
    year: "2008",
    genre: "Sci-fi",
    type: "movie",
    director: "Scott Derrickson",
    maincast: "Keanu Reeves, Jennifer Connelly",
    img: "https://m.media-amazon.com/images/M/MV5BMTI5NTg1MzU5Nl5BMl5BanBnXkFtZTcwMDc0MTUyMQ@@._V1_.jpg",
    rating: 3,
    isFeatured: false,
    isTrending: false,
    link: "o7jR6SIcSr8",
  },
  {
    title: "Elysium",
    year: "2013",
    genre: "Sci-fi",
    type: "movie",
    director: "Neill Blomkamp",
    maincast: "Matt Damon, Jodie Foster, Sharlto Copley",
    img: "https://m.media-amazon.com/images/M/MV5BNDc2NjU0MTcwNV5BMl5BanBnXkFtZTcwMjg4MDg2OQ@@._V1_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "oIBtePb-dGY",
  },
  // ============ BATCH 5: HORROR MOVIES ============
  {
    title: "The Shining",
    year: "1980",
    genre: "Horror",
    type: "movie",
    director: "Stanley Kubrick",
    maincast: "Jack Nicholson, Shelley Duvall",
    img: "https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "5Cb3ik6zP2I",
  },
  {
    title: "The Exorcist",
    year: "1973",
    genre: "Horror",
    type: "movie",
    director: "William Friedkin",
    maincast: "Ellen Burstyn, Max von Sydow, Linda Blair",
    img: "https://m.media-amazon.com/images/M/MV5BYWFlZGY2NDktY2ZjOS00ZWNkLTg0ZDAtZDY4MTM1ODU4ZjljXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "YDGw1MTEe9k",
  },
  {
    title: "Hereditary",
    year: "2018",
    genre: "Horror",
    type: "movie",
    director: "Ari Aster",
    maincast: "Toni Collette, Milly Shapiro, Gabriel Byrne",
    img: "https://m.media-amazon.com/images/M/MV5BOTU5MDg3OGItZWQ1Ny00ZGVmLTg2YTUtMzBkYzQ1YWIwZjlhXkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "V6wWKNij_1M",
  },
  {
    title: "Midsommar",
    year: "2019",
    genre: "Horror",
    type: "movie",
    director: "Ari Aster",
    maincast: "Florence Pugh, Jack Reynor, William Jackson Harper",
    img: "https://m.media-amazon.com/images/M/MV5BMzQxNzQzOTQwM15BMl5BanBnXkFtZTgwMDQ2NTcwODM@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "1Vnghdsjmd0",
  },
  {
    title: "The Ring",
    year: "2002",
    genre: "Horror",
    type: "movie",
    director: "Gore Verbinski",
    maincast: "Naomi Watts, Martin Henderson",
    img: "https://m.media-amazon.com/images/M/MV5BNDA2NTg0NTUyNV5BMl5BanBnXkFtZTYwMjcxNjM3._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "yzR2GY-ew8I",
  },
  {
    title: "Sinister",
    year: "2012",
    genre: "Horror",
    type: "movie",
    director: "Scott Derrickson",
    maincast: "Ethan Hawke, Juliet Rylance",
    img: "https://m.media-amazon.com/images/M/MV5BMzg5NTI0NTc1N15BMl5BanBnXkFtZTcwNjA4MjMyOA@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "2d9ykw1fV0Q",
  },
  {
    title: "Insidious",
    year: "2010",
    genre: "Horror",
    type: "movie",
    director: "James Wan",
    maincast: "Patrick Wilson, Rose Byrne, Ty Simpkins",
    img: "https://m.media-amazon.com/images/M/MV5BMTYyOTAxMDA0OF5BMl5BanBnXkFtZTcwNzgwNTc1NA@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "zuZnRUcoWos",
  },
  {
    title: "The Babadook",
    year: "2014",
    genre: "Horror",
    type: "movie",
    director: "Jennifer Kent",
    maincast: "Essie Davis, Noah Wiseman",
    img: "https://m.media-amazon.com/images/M/MV5BMTk0NzMzODc2NF5BMl5BanBnXkFtZTgwOTYzNTM1MzE@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "szaLnKfKlTw",
  },
  {
    title: "Us",
    year: "2019",
    genre: "Horror",
    type: "movie",
    director: "Jordan Peele",
    maincast: "Lupita Nyong'o, Winston Duke, Elisabeth Moss",
    img: "https://m.media-amazon.com/images/M/MV5BZTliNWJhM2YtNDc1MC00YTk1LWE2MGYtZmE4M2Y5ODdlNzQzXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "hNCmb-4oXJA",
  },
  {
    title: "The Witch",
    year: "2015",
    genre: "Horror",
    type: "movie",
    director: "Robert Eggers",
    maincast: "Anya Taylor-Joy, Ralph Ineson",
    img: "https://m.media-amazon.com/images/M/MV5BMTUyNzkwMzAxOF5BMl5BanBnXkFtZTgwMzc1OTk1NjE@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "iQXmlf3Sefg",
  },
  // ============ BATCH 6: MORE HORROR MOVIES ============
  {
    title: "The Lighthouse",
    year: "2019",
    genre: "Horror",
    type: "movie",
    director: "Robert Eggers",
    maincast: "Willem Dafoe, Robert Pattinson",
    img: "https://m.media-amazon.com/images/M/MV5BZmE0MGJhNmYtOWNjYi00Njc5LWE2YjEtMWMxZTVmODUwMmMxXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "Hyag7lR8CPA",
  },
  {
    title: "The Cabin in the Woods",
    year: "2011",
    genre: "Horror",
    type: "movie",
    director: "Drew Goddard",
    maincast: "Kristen Connolly, Chris Hemsworth, Fran Kranz",
    img: "https://m.media-amazon.com/images/M/MV5BNTUxNzYyMjg2N15BMl5BanBnXkFtZTcwMTExNzExNw@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "NsIilFNNmkY",
  },
  {
    title: "28 Days Later",
    year: "2002",
    genre: "Horror",
    type: "movie",
    director: "Danny Boyle",
    maincast: "Cillian Murphy, Naomie Harris",
    img: "https://m.media-amazon.com/images/M/MV5BNzM2YWJiMzgtMGE4MC00M2E0LTk0NjAtNTU3ZGIzNDdhNTRmXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "c7ynwAgQlDQ",
  },
  {
    title: "Scream",
    year: "1996",
    genre: "Horror",
    type: "movie",
    director: "Wes Craven",
    maincast: "Neve Campbell, Courteney Cox, David Arquette",
    img: "https://m.media-amazon.com/images/M/MV5BMjA2NjU5MTg5OF5BMl5BanBnXkFtZTgwOTkyMzQxMDE@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "AWm_mkbdpCA",
  },
  {
    title: "A Nightmare on Elm Street",
    year: "1984",
    genre: "Horror",
    type: "movie",
    director: "Wes Craven",
    maincast: "Robert Englund, Heather Langenkamp",
    img: "https://m.media-amazon.com/images/M/MV5BNzFjZmM1ODgtMDBkMS00NWFlLTg2YmUtZjc3ZTgxMjE1OTI2L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "dCVh4lBfW-c",
  },
  {
    title: "Halloween",
    year: "1978",
    genre: "Horror",
    type: "movie",
    director: "John Carpenter",
    maincast: "Jamie Lee Curtis, Donald Pleasence",
    img: "https://m.media-amazon.com/images/M/MV5BNzk1OGU2NmMtNTdhZC00NjdlLWE5YTMtZTQ0MGExZTQzOGQyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "T5ke9IPTIJQ",
  },
  {
    title: "Friday the 13th",
    year: "1980",
    genre: "Horror",
    type: "movie",
    director: "Sean S. Cunningham",
    maincast: "Betsy Palmer, Adrienne King",
    img: "https://m.media-amazon.com/images/M/MV5BNWMxOGZjMzMtMGYxNi00NjkxLWE4NTctMzQ4YzUxM2FiMGY0L2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "Xqqej9T2gqI",
  },
  {
    title: "The Texas Chain Saw Massacre",
    year: "1974",
    genre: "Horror",
    type: "movie",
    director: "Tobe Hooper",
    maincast: "Marilyn Burns, Gunnar Hansen",
    img: "https://m.media-amazon.com/images/M/MV5BNGFlNjJlNGQtNDNjNC00ZGMxLWFlYzQtMGNjZTlkZWE1MDZiL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "Vs3981DoINw",
  },
  {
    title: "Saw",
    year: "2004",
    genre: "Horror",
    type: "movie",
    director: "James Wan",
    maincast: "Cary Elwes, Leigh Whannell, Danny Glover",
    img: "https://m.media-amazon.com/images/M/MV5BMjAzMzEzOTMxNF5BMl5BanBnXkFtZTcwNjc4Mjc5Mw@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "S-1QgOMQ-ls",
  },
  {
    title: "The Descent",
    year: "2005",
    genre: "Horror",
    type: "movie",
    director: "Neil Marshall",
    maincast: "Shauna Macdonald, Natalie Mendoza",
    img: "https://m.media-amazon.com/images/M/MV5BMjA5NzQ1NTgwNV5BMl5BanBnXkFtZTcwNjUxMzUzMw@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "4bOTNHsEMPU",
  },
  // ============ BATCH 7: COMEDY MOVIES ============
  {
    title: "The 40-Year-Old Virgin",
    year: "2005",
    genre: "Comedy",
    type: "movie",
    director: "Judd Apatow",
    maincast: "Steve Carell, Catherine Keener, Paul Rudd",
    img: "https://m.media-amazon.com/images/M/MV5BMTMzODE0ODA4NV5BMl5BanBnXkFtZTcwMzI4MjEzMQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "eSXckNMNzJM",
  },
  {
    title: "Bridesmaids",
    year: "2011",
    genre: "Comedy",
    type: "movie",
    director: "Paul Feig",
    maincast: "Kristen Wiig, Maya Rudolph, Rose Byrne",
    img: "https://m.media-amazon.com/images/M/MV5BMjAyOTgxMzE4OV5BMl5BanBnXkFtZTcwMjkxNjc1NA@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "FNppLrmdyug",
  },
  {
    title: "Step Brothers",
    year: "2008",
    genre: "Comedy",
    type: "movie",
    director: "Adam McKay",
    maincast: "Will Ferrell, John C. Reilly",
    img: "https://m.media-amazon.com/images/M/MV5BODgxN2U2MWYtNGRhYy00OTIzLTlkZTAtZTBiMjJlMTMzZmQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "CewglxElBK0",
  },
  {
    title: "Anchorman",
    year: "2004",
    genre: "Comedy",
    type: "movie",
    director: "Adam McKay",
    maincast: "Will Ferrell, Christina Applegate, Steve Carell",
    img: "https://m.media-amazon.com/images/M/MV5BMTQ2MzYwMzk5Ml5BMl5BanBnXkFtZTcwOTI4NzUyMQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "QVs0FR_gKBo",
  },
  {
    title: "Elf",
    year: "2003",
    genre: "Comedy",
    type: "movie",
    director: "Jon Favreau",
    maincast: "Will Ferrell, James Caan, Zooey Deschanel",
    img: "https://m.media-amazon.com/images/M/MV5BMzUxNzkzMzQtYjIxZC00NjFmLWIwMDUtZGQ0MjAyZjBhOTZlXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "gMcJVoLwyD0",
  },
  {
    title: "Dumb and Dumber",
    year: "1994",
    genre: "Comedy",
    type: "movie",
    director: "Peter Farrelly",
    maincast: "Jim Carrey, Jeff Daniels, Lauren Holly",
    img: "https://m.media-amazon.com/images/M/MV5BZDQwMjNiMTQtY2UwYy00NjhiLTk0ZWEtZWM5ZWMzNGFjNTVkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "ye7SYhbS4c0",
  },
  {
    title: "Ace Ventura: Pet Detective",
    year: "1994",
    genre: "Comedy",
    type: "movie",
    director: "Tom Shadyac",
    maincast: "Jim Carrey, Courteney Cox, Sean Young",
    img: "https://m.media-amazon.com/images/M/MV5BYmVhNmFmOGYtZjgwNi00ZGQ0LThiMmQtOGZjMDMwZDYzZDQ2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "LVd85E6qY7w",
  },
  {
    title: "The Mask",
    year: "1994",
    genre: "Comedy",
    type: "movie",
    director: "Chuck Russell",
    maincast: "Jim Carrey, Cameron Diaz, Peter Riegert",
    img: "https://m.media-amazon.com/images/M/MV5BOTk3NzMwODU5MV5BMl5BanBnXkFtZTcwODQ5MzIyMQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "LZl69ik5lEY",
  },
  {
    title: "Liar Liar",
    year: "1997",
    genre: "Comedy",
    type: "movie",
    director: "Tom Shadyac",
    maincast: "Jim Carrey, Maura Tierney, Justin Cooper",
    img: "https://m.media-amazon.com/images/M/MV5BYTM3OTc2MWUtZDNhOS00OWViLTgxZjQtMzEwM2JlZTBlOGIyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "o7sDjwqk-KY",
  },
  {
    title: "Bruce Almighty",
    year: "2003",
    genre: "Comedy",
    type: "movie",
    director: "Tom Shadyac",
    maincast: "Jim Carrey, Morgan Freeman, Jennifer Aniston",
    img: "https://m.media-amazon.com/images/M/MV5BNzMyZDhiZDUtYWUyMi00ZDQxLWE4NDYtNmZhNWFkMTYyMTI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "HDk4Y6xVkdM",
  },
  // ============ BATCH 8: MORE COMEDY MOVIES ============
  {
    title: "Groundhog Day",
    year: "1993",
    genre: "Comedy",
    type: "movie",
    director: "Harold Ramis",
    maincast: "Bill Murray, Andie MacDowell, Chris Elliott",
    img: "https://m.media-amazon.com/images/M/MV5BZWIxNzM5NzQtY2FmMS00Yjc3LWI1ZjUtNGVjMjMzZTIxZTIxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "GncQtURdcE4",
  },
  {
    title: "Ghostbusters",
    year: "1984",
    genre: "Comedy",
    type: "movie",
    director: "Ivan Reitman",
    maincast: "Bill Murray, Dan Aykroyd, Sigourney Weaver",
    img: "https://m.media-amazon.com/images/M/MV5BMTkxMjYyNzgwMl5BMl5BanBnXkFtZTgwMTE3MjYyMTE@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "6hDkhw5Wkas",
  },
  {
    title: "Coming to America",
    year: "1988",
    genre: "Comedy",
    type: "movie",
    director: "John Landis",
    maincast: "Eddie Murphy, Arsenio Hall, James Earl Jones",
    img: "https://m.media-amazon.com/images/M/MV5BYmQxMmU2ZjMtNWI0Ni00MTFiLTgyNjAtMDdmMzRkMjEyNzc1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "Qa0aeJzNVPM",
  },
  {
    title: "Trading Places",
    year: "1983",
    genre: "Comedy",
    type: "movie",
    director: "John Landis",
    maincast: "Eddie Murphy, Dan Aykroyd, Jamie Lee Curtis",
    img: "https://m.media-amazon.com/images/M/MV5BMTU4NDUyNzA2N15BMl5BanBnXkFtZTgwMTE1NTYxMTE@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "zGk5U5dX0Pk",
  },
  {
    title: "Ferris Bueller's Day Off",
    year: "1986",
    genre: "Comedy",
    type: "movie",
    director: "John Hughes",
    maincast: "Matthew Broderick, Alan Ruck, Mia Sara",
    img: "https://m.media-amazon.com/images/M/MV5BMDA0NjZhZWUtNmI2NC00MmFjLTgwZDYtYzVjZmNhMDVmOTBkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "R-P6p86px6U",
  },
  {
    title: "The Breakfast Club",
    year: "1985",
    genre: "Comedy",
    type: "movie",
    director: "John Hughes",
    maincast: "Emilio Estevez, Judd Nelson, Molly Ringwald",
    img: "https://m.media-amazon.com/images/M/MV5BOTM5N2NmNDItMjg5NS00NGNkLTllMDMtMTFmZWQwMjM2OGNjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "BSXBvor47Zs",
  },
  {
    title: "Sixteen Candles",
    year: "1984",
    genre: "Comedy",
    type: "movie",
    director: "John Hughes",
    maincast: "Molly Ringwald, Anthony Michael Hall",
    img: "https://m.media-amazon.com/images/M/MV5BMjNhYjI1ZjMtNDg3OC00MmRlLTg5MjgtNzE0Yzk4ODRkZjE2XkEyXkFqcGdeQXVyNDAxNjkxNjQ@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "7xkG2Jqs7mo",
  },
  {
    title: "21 Jump Street",
    year: "2012",
    genre: "Comedy",
    type: "movie",
    director: "Phil Lord, Christopher Miller",
    maincast: "Jonah Hill, Channing Tatum, Ice Cube",
    img: "https://m.media-amazon.com/images/M/MV5BMTc3NTM4MzQ5MV5BMl5BanBnXkFtZTcwNjc2NzE5Ng@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "RLoKtb4c4W0",
  },
  {
    title: "Neighbors",
    year: "2014",
    genre: "Comedy",
    type: "movie",
    director: "Nicholas Stoller",
    maincast: "Seth Rogen, Zac Efron, Rose Byrne",
    img: "https://m.media-amazon.com/images/M/MV5BOTM3NTQzMjA4M15BMl5BanBnXkFtZTgwODgyMDg2MTE@._V1_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "kL5c0HJTolI",
  },
  {
    title: "This Is the End",
    year: "2013",
    genre: "Comedy",
    type: "movie",
    director: "Seth Rogen, Evan Goldberg",
    maincast: "James Franco, Seth Rogen, Jonah Hill",
    img: "https://m.media-amazon.com/images/M/MV5BMTQxODE3NjM1Ml5BMl5BanBnXkFtZTcwMzkzNjc4OA@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "66cI81vQGtE",
  },
  // ============ BATCH 9: DRAMA MOVIES ============
  {
    title: "The Shawshank Redemption",
    year: "1994",
    genre: "Drama",
    type: "movie",
    director: "Frank Darabont",
    maincast: "Tim Robbins, Morgan Freeman",
    img: "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
    rating: 5,
    isFeatured: false,
    isTrending: false,
    link: "6hB3S9bIaco",
  },
  {
    title: "Forrest Gump",
    year: "1994",
    genre: "Drama",
    type: "movie",
    director: "Robert Zemeckis",
    maincast: "Tom Hanks, Robin Wright, Gary Sinise",
    img: "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 5,
    isFeatured: false,
    isTrending: false,
    link: "bLvqoHBptjg",
  },
  {
    title: "The Green Mile",
    year: "1999",
    genre: "Drama",
    type: "movie",
    director: "Frank Darabont",
    maincast: "Tom Hanks, Michael Clarke Duncan",
    img: "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "ctRK-4Vt7dA",
  },
  {
    title: "Schindler's List",
    year: "1993",
    genre: "Drama",
    type: "movie",
    director: "Steven Spielberg",
    maincast: "Liam Neeson, Ralph Fiennes, Ben Kingsley",
    img: "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 5,
    isFeatured: false,
    isTrending: false,
    link: "gG22XNhtnoY",
  },
  {
    title: "Fight Club",
    year: "1999",
    genre: "Drama",
    type: "movie",
    director: "David Fincher",
    maincast: "Brad Pitt, Edward Norton, Helena Bonham Carter",
    img: "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "qtRKdVHc-cE",
  },
  {
    title: "The Departed",
    year: "2006",
    genre: "Drama",
    type: "movie",
    director: "Martin Scorsese",
    maincast: "Leonardo DiCaprio, Matt Damon, Jack Nicholson",
    img: "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "iQpb1LoeVUc",
  },
  {
    title: "Goodfellas",
    year: "1990",
    genre: "Drama",
    type: "movie",
    director: "Martin Scorsese",
    maincast: "Robert De Niro, Ray Liotta, Joe Pesci",
    img: "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "2ilzidi_J8Q",
  },
  {
    title: "The Silence of the Lambs",
    year: "1991",
    genre: "Drama",
    type: "movie",
    director: "Jonathan Demme",
    maincast: "Jodie Foster, Anthony Hopkins",
    img: "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "W6Mm8Sbe__o",
  },
  {
    title: "Se7en",
    year: "1995",
    genre: "Drama",
    type: "movie",
    director: "David Fincher",
    maincast: "Brad Pitt, Morgan Freeman, Kevin Spacey",
    img: "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "znmZoVkCjpI",
  },
  {
    title: "The Prestige",
    year: "2006",
    genre: "Drama",
    type: "movie",
    director: "Christopher Nolan",
    maincast: "Christian Bale, Hugh Jackman, Scarlett Johansson",
    img: "https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "o4gHCmTQDVI",
  },
  // ============ BATCH 10: TV SHOWS ============
  {
    title: "Game of Thrones",
    year: "2011",
    genre: "Drama",
    type: "tv",
    director: "David Benioff, D.B. Weiss",
    maincast: "Emilia Clarke, Kit Harington, Peter Dinklage",
    img: "https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "KPLWWIOCOOQ",
  },
  {
    title: "The Walking Dead",
    year: "2010",
    genre: "Horror",
    type: "tv",
    director: "Frank Darabont",
    maincast: "Andrew Lincoln, Norman Reedus, Melissa McBride",
    img: "https://m.media-amazon.com/images/M/MV5BZmU5NTcwNjktODYwMi00NTAyLThiNTMtZmQ4ZDkwZDM4YTcwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "R1v0uFms68U",
  },
  {
    title: "The Office",
    year: "2005",
    genre: "Comedy",
    type: "tv",
    director: "Greg Daniels",
    maincast: "Steve Carell, Rainn Wilson, John Krasinski",
    img: "https://m.media-amazon.com/images/M/MV5BMDNkOTE4NDQtMTNmYi00MWE0LWE4ZTktYTc0NzhhNWIzNzJiXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "LHOtME2DL4g",
  },
  {
    title: "Friends",
    year: "1994",
    genre: "Comedy",
    type: "tv",
    director: "David Crane, Marta Kauffman",
    maincast: "Jennifer Aniston, Courteney Cox, Lisa Kudrow",
    img: "https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "hDNNmeeJs1Q",
  },
  {
    title: "The Mandalorian",
    year: "2019",
    genre: "Sci-fi",
    type: "tv",
    director: "Jon Favreau",
    maincast: "Pedro Pascal, Giancarlo Esposito",
    img: "https://m.media-amazon.com/images/M/MV5BZDhlMzY0ZGItZTcyNS00ZTAxLWIyMmYtZGQ2ODg5OWZiYmJkXkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "aOC8E8z_ifw",
  },
  {
    title: "Peaky Blinders",
    year: "2013",
    genre: "Drama",
    type: "tv",
    director: "Steven Knight",
    maincast: "Cillian Murphy, Paul Anderson, Helen McCrory",
    img: "https://m.media-amazon.com/images/M/MV5BZjZlMTIwNTctNjA4NC00NmQyLTg4MjctNjg4N2IzOTU5YTY5XkEyXkFqcGdeQXVyMTE5NDQ1MzQ3._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "oVzVdvGIC7U",
  },
  {
    title: "Money Heist",
    year: "2017",
    genre: "Action",
    type: "tv",
    director: "Álex Pina",
    maincast: "Úrsula Corberó, Álvaro Morte, Itziar Ituño",
    img: "https://m.media-amazon.com/images/M/MV5BODI0ZTljYTMtODQ1NC00NmI0LTk1YWUtN2FlNDM1MDExMDlhXkEyXkFqcGdeQXVyMTM0NTUzNDIy._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "_InqQJRqGW4",
  },
  {
    title: "Squid Game",
    year: "2021",
    genre: "Drama",
    type: "tv",
    director: "Hwang Dong-hyuk",
    maincast: "Lee Jung-jae, Park Hae-soo, Wi Ha-joon",
    img: "https://m.media-amazon.com/images/M/MV5BYWE3MDVkN2EtNjQ5MS00ZDQ4LTliNzYtMjc2YWMzMDEwMTA3XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "oqxAJKy0ii4",
  },
  {
    title: "The Crown",
    year: "2016",
    genre: "Drama",
    type: "tv",
    director: "Peter Morgan",
    maincast: "Claire Foy, Olivia Colman, Imelda Staunton",
    img: "https://m.media-amazon.com/images/M/MV5BZTMyYjg0MGMtMGJmMi00ODU5LWIxZGMtZDdjNjcxYzZlMDJiXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "JWtnJjn6ng0",
  },
  {
    title: "Ozark",
    year: "2017",
    genre: "Drama",
    type: "tv",
    director: "Bill Dubuque, Mark Williams",
    maincast: "Jason Bateman, Laura Linney, Julia Garner",
    img: "https://m.media-amazon.com/images/M/MV5BZDNkZmRlYTUtMTYwNS00MzgxLTk1NDAtNzc3YTlkMjU4NzllXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "5hAXVqrljbs",
  },
  // ============ BATCH 11: MORE TV SHOWS ============
  {
    title: "The Witcher",
    year: "2019",
    genre: "Action",
    type: "tv",
    director: "Lauren Schmidt Hissrich",
    maincast: "Henry Cavill, Freya Allan, Anya Chalotra",
    img: "https://m.media-amazon.com/images/M/MV5BMDEwOTRmNWQtODI4OS00NGZhLWE5NTctNmNiMjA5YjcyMmU1XkEyXkFqcGdeQXVyNjgzMTMxOTU@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: true,
    link: "ndl1W4ltcmg",
  },
  {
    title: "House of the Dragon",
    year: "2022",
    genre: "Drama",
    type: "tv",
    director: "Ryan Condal, George R.R. Martin",
    maincast: "Paddy Considine, Emma D'Arcy, Matt Smith",
    img: "https://m.media-amazon.com/images/M/MV5BZDBkZjRiNGMtZGU2My00ODdkLWI0MGUtNjAzNjBiYTJlMzc1XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "DotnJ7tTA34",
  },
  {
    title: "Succession",
    year: "2018",
    genre: "Drama",
    type: "tv",
    director: "Jesse Armstrong",
    maincast: "Brian Cox, Jeremy Strong, Sarah Snook",
    img: "https://m.media-amazon.com/images/M/MV5BZWE0YjE0MmItNDQ5Yi00MWU0LTgxZmQtNjQxNDk0Yjg4YjQ1XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "OzYxJV_rmE8",
  },
  {
    title: "The Last of Us",
    year: "2023",
    genre: "Drama",
    type: "tv",
    director: "Craig Mazin, Neil Druckmann",
    maincast: "Pedro Pascal, Bella Ramsey, Anna Torv",
    img: "https://m.media-amazon.com/images/M/MV5BZGUzYTI3M2EtZmM0Yy00NGUyLWI4ODEtN2Q3ZGJlYzhhZjU3XkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "uLtkt8BonwM",
  },
  {
    title: "Sherlock",
    year: "2010",
    genre: "Drama",
    type: "tv",
    director: "Mark Gatiss, Steven Moffat",
    maincast: "Benedict Cumberbatch, Martin Freeman",
    img: "https://m.media-amazon.com/images/M/MV5BMWEzNTFlMTQtMzhjOS00MzQ1LWJjNjgtY2RhMjliMWQzODM2XkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "gGqWqGOSTzs",
  },
  {
    title: "The Boys",
    year: "2019",
    genre: "Action",
    type: "tv",
    director: "Eric Kripke",
    maincast: "Karl Urban, Jack Quaid, Antony Starr",
    img: "https://m.media-amazon.com/images/M/MV5BMjIwMDY2NTI2Nl5BMl5BanBnXkFtZTgwNjU5NDQ1NjM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "M1bhOaLV4FU",
  },
  {
    title: "Dark",
    year: "2017",
    genre: "Sci-fi",
    type: "tv",
    director: "Baran bo Odar, Jantje Friese",
    maincast: "Louis Hofmann, Oliver Masucci",
    img: "https://m.media-amazon.com/images/M/MV5BMjE3MDM5MzUxNF5BMl5BanBnXkFtZTgwMzg1MDEzNTI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "rrwycJ08PSA",
  },
  {
    title: "Westworld",
    year: "2016",
    genre: "Sci-fi",
    type: "tv",
    director: "Jonathan Nolan, Lisa Joy",
    maincast: "Evan Rachel Wood, Thandiwe Newton, Jeffrey Wright",
    img: "https://m.media-amazon.com/images/M/MV5BMTRmYzNmOTctZjMwOS00ODZlLWJiZGQtNDg5NDY5NjE3MTczXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "9BqKiDSJaAs",
  },
  {
    title: "Black Mirror",
    year: "2011",
    genre: "Sci-fi",
    type: "tv",
    director: "Charlie Brooker",
    maincast: "Various",
    img: "https://m.media-amazon.com/images/M/MV5BYTM3YWVhMDMtNjczMy00NGEyLWJhZDctYjNhMTRkNDE0ZTI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "di6emt8_ie8",
  },
  {
    title: "Mindhunter",
    year: "2017",
    genre: "Drama",
    type: "tv",
    director: "Joe Penhall",
    maincast: "Jonathan Groff, Holt McCallany, Anna Torv",
    img: "https://m.media-amazon.com/images/M/MV5BNmNkZTFiMzktZGJlYy00YjVjLWE2OTYtNTdhM2MzZmU3Y2I1XkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "oFlKiLjhfBo",
  },
  // ============ BATCH 12: ANIMATED MOVIES ============
  {
    title: "Spirited Away",
    year: "2001",
    genre: "Animated",
    type: "movie",
    director: "Hayao Miyazaki",
    maincast: "Rumi Hiiragi, Miyu Irino, Mari Natsuki",
    img: "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: false,
    link: "ByXuk9QqQkk",
  },
  {
    title: "The Lion King",
    year: "1994",
    genre: "Animated",
    type: "movie",
    director: "Roger Allers, Rob Minkoff",
    maincast: "Matthew Broderick, James Earl Jones, Jeremy Irons",
    img: "https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "4sj1MT05lAA",
  },
  {
    title: "Toy Story",
    year: "1995",
    genre: "Animated",
    type: "movie",
    director: "John Lasseter",
    maincast: "Tom Hanks, Tim Allen, Don Rickles",
    img: "https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "v-PjgYDrg70",
  },
  {
    title: "Finding Nemo",
    year: "2003",
    genre: "Animated",
    type: "movie",
    director: "Andrew Stanton, Lee Unkrich",
    maincast: "Albert Brooks, Ellen DeGeneres, Alexander Gould",
    img: "https://m.media-amazon.com/images/M/MV5BZTAzNWZlNmUtZDEzYi00ZjA5LWIwYjEtZGM1NWE1MjE4YWRhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "9oQ628Seb9w",
  },
  {
    title: "Up",
    year: "2009",
    genre: "Animated",
    type: "movie",
    director: "Pete Docter, Bob Peterson",
    maincast: "Ed Asner, Jordan Nagai, Christopher Plummer",
    img: "https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "ORFWdXl_zJ4",
  },
  {
    title: "WALL-E",
    year: "2008",
    genre: "Animated",
    type: "movie",
    director: "Andrew Stanton",
    maincast: "Ben Burtt, Elissa Knight, Jeff Garlin",
    img: "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "CZ1CATNbXg0",
  },
  {
    title: "Coco",
    year: "2017",
    genre: "Animated",
    type: "movie",
    director: "Lee Unkrich, Adrian Molina",
    maincast: "Anthony Gonzalez, Gael García Bernal, Benjamin Bratt",
    img: "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "Rvr68u6k5sI",
  },
  {
    title: "Inside Out",
    year: "2015",
    genre: "Animated",
    type: "movie",
    director: "Pete Docter, Ronnie Del Carmen",
    maincast: "Amy Poehler, Bill Hader, Lewis Black",
    img: "https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "seMwpP0yeu4",
  },
  {
    title: "Frozen",
    year: "2013",
    genre: "Animated",
    type: "movie",
    director: "Chris Buck, Jennifer Lee",
    maincast: "Kristen Bell, Idina Menzel, Josh Gad",
    img: "https://m.media-amazon.com/images/M/MV5BMTQ1MjQwMTE5OF5BMl5BanBnXkFtZTgwNjk3MTcyMDE@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "TbQm5doF_Uc",
  },
  {
    title: "Zootopia",
    year: "2016",
    genre: "Animated",
    type: "movie",
    director: "Byron Howard, Rich Moore",
    maincast: "Ginnifer Goodwin, Jason Bateman, Idris Elba",
    img: "https://m.media-amazon.com/images/M/MV5BOTMyMjEyNzIzMV5BMl5BanBnXkFtZTgwNzIyNjU0NzE@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "jWM0ct-OLsM",
  },
  // ============ BATCH 13: MORE ANIMATED MOVIES ============
  {
    title: "Shrek",
    year: "2001",
    genre: "Animated",
    type: "movie",
    director: "Andrew Adamson, Vicky Jenson",
    maincast: "Mike Myers, Eddie Murphy, Cameron Diaz",
    img: "https://m.media-amazon.com/images/M/MV5BOGZhM2FhNTItODAzNi00YjA0LWEyN2UtNjJlYWQzYzU1MDg5L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "CwXOrWvPBPk",
  },
  {
    title: "Monsters, Inc.",
    year: "2001",
    genre: "Animated",
    type: "movie",
    director: "Pete Docter",
    maincast: "Billy Crystal, John Goodman, Steve Buscemi",
    img: "https://m.media-amazon.com/images/M/MV5BMTY1NTI0ODUyOF5BMl5BanBnXkFtZTgwNTEyNjQ0MDE@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "8IBNZ6O2kMk",
  },
  {
    title: "The Incredibles",
    year: "2004",
    genre: "Animated",
    type: "movie",
    director: "Brad Bird",
    maincast: "Craig T. Nelson, Holly Hunter, Samuel L. Jackson",
    img: "https://m.media-amazon.com/images/M/MV5BMTY5OTU0OTc2NV5BMl5BanBnXkFtZTcwMzU4MDcyMQ@@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "-UaGUdNJdRQ",
  },
  {
    title: "Ratatouille",
    year: "2007",
    genre: "Animated",
    type: "movie",
    director: "Brad Bird, Jan Pinkava",
    maincast: "Patton Oswalt, Ian Holm, Lou Romano",
    img: "https://m.media-amazon.com/images/M/MV5BMTMzODU0NTkxMF5BMl5BanBnXkFtZTcwMjQ4MzMzMw@@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "c3sBBRxDAqk",
  },
  {
    title: "How to Train Your Dragon",
    year: "2010",
    genre: "Animated",
    type: "movie",
    director: "Dean DeBlois, Chris Sanders",
    maincast: "Jay Baruchel, Gerard Butler, Craig Ferguson",
    img: "https://m.media-amazon.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "oKiYuIsPxYk",
  },
  {
    title: "My Neighbor Totoro",
    year: "1988",
    genre: "Animated",
    type: "movie",
    director: "Hayao Miyazaki",
    maincast: "Hitoshi Takagi, Noriko Hidaka, Chika Sakamoto",
    img: "https://m.media-amazon.com/images/M/MV5BYzJjMTYyMjQtZDI0My00ZjE2LTkyNGYtOTllNGQxNDMyZjE0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "92a7Hj0ijLs",
  },
  {
    title: "Princess Mononoke",
    year: "1997",
    genre: "Animated",
    type: "movie",
    director: "Hayao Miyazaki",
    maincast: "Yoji Matsuda, Yuriko Ishida, Yuko Tanaka",
    img: "https://m.media-amazon.com/images/M/MV5BNGIzY2IzODQtNThmMi00ZDE4LWI5YzAtNzNlZTM1ZjYyYjUyXkEyXkFqcGdeQXVyODEzNjM5OTQ@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "4OiMOHRDs14",
  },
  {
    title: "Howl's Moving Castle",
    year: "2004",
    genre: "Animated",
    type: "movie",
    director: "Hayao Miyazaki",
    maincast: "Chieko Baisho, Takuya Kimura, Akihiro Miwa",
    img: "https://m.media-amazon.com/images/M/MV5BNmM4YTFmMmItMGE3Yy00MmRkLTlmZGEtMzZlOTQzYjk3MzA2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "iwROgK94zcM",
  },
  {
    title: "Despicable Me",
    year: "2010",
    genre: "Animated",
    type: "movie",
    director: "Pierre Coffin, Chris Renaud",
    maincast: "Steve Carell, Jason Segel, Russell Brand",
    img: "https://m.media-amazon.com/images/M/MV5BMTY3NjY0MTQ0Nl5BMl5BanBnXkFtZTcwMzQ2MTc0Mw@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "sUkZFetWYY0",
  },
  {
    title: "Kung Fu Panda",
    year: "2008",
    genre: "Animated",
    type: "movie",
    director: "Mark Osborne, John Stevenson",
    maincast: "Jack Black, Dustin Hoffman, Angelina Jolie",
    img: "https://m.media-amazon.com/images/M/MV5BODJkZTZhMWItMDI3Yy00ZWZlLTk4NjQtOTI1ZjU5NjBjZTVjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "PXi3Mv6KMzY",
  },
  // ============ BATCH 14: MORE DRAMA MOVIES ============
  {
    title: "The Godfather",
    year: "1972",
    genre: "Drama",
    type: "movie",
    director: "Francis Ford Coppola",
    maincast: "Marlon Brando, Al Pacino, James Caan",
    img: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 5,
    isFeatured: true,
    isTrending: false,
    link: "UaVTIH8mujA",
  },
  {
    title: "The Godfather Part II",
    year: "1974",
    genre: "Drama",
    type: "movie",
    director: "Francis Ford Coppola",
    maincast: "Al Pacino, Robert De Niro, Robert Duvall",
    img: "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 5,
    isFeatured: false,
    isTrending: false,
    link: "OA1ij0alE0w",
  },
  {
    title: "Pulp Fiction",
    year: "1994",
    genre: "Drama",
    type: "movie",
    director: "Quentin Tarantino",
    maincast: "John Travolta, Uma Thurman, Samuel L. Jackson",
    img: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "s7EdQ4FqbhY",
  },
  {
    title: "12 Angry Men",
    year: "1957",
    genre: "Drama",
    type: "movie",
    director: "Sidney Lumet",
    maincast: "Henry Fonda, Lee J. Cobb, Martin Balsam",
    img: "https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "_13J_9B5jEk",
  },
  {
    title: "One Flew Over the Cuckoo's Nest",
    year: "1975",
    genre: "Drama",
    type: "movie",
    director: "Milos Forman",
    maincast: "Jack Nicholson, Louise Fletcher, Will Sampson",
    img: "https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "OXrcDonY-B8",
  },
  {
    title: "A Beautiful Mind",
    year: "2001",
    genre: "Drama",
    type: "movie",
    director: "Ron Howard",
    maincast: "Russell Crowe, Ed Harris, Jennifer Connelly",
    img: "https://m.media-amazon.com/images/M/MV5BMzcwYWFkYzktZjAzNC00OGY1LWI4YTctNjE0NjY0ZDIyMTVlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "aS_d0Ayjm4o",
  },
  {
    title: "The Pianist",
    year: "2002",
    genre: "Drama",
    type: "movie",
    director: "Roman Polanski",
    maincast: "Adrien Brody, Thomas Kretschmann, Frank Finlay",
    img: "https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "u_jE0T-NK3s",
  },
  {
    title: "The Social Network",
    year: "2010",
    genre: "Drama",
    type: "movie",
    director: "David Fincher",
    maincast: "Jesse Eisenberg, Andrew Garfield, Justin Timberlake",
    img: "https://m.media-amazon.com/images/M/MV5BOGUyZDUxZjEtMmIzMC00MzlmLTg4MGItZWJmMzBhZjE0Mjc1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "lB95KLmpLR4",
  },
  {
    title: "Whiplash",
    year: "2014",
    genre: "Drama",
    type: "movie",
    director: "Damien Chazelle",
    maincast: "Miles Teller, J.K. Simmons, Melissa Benoist",
    img: "https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "7d_jQycdQGo",
  },
  {
    title: "The Wolf of Wall Street",
    year: "2013",
    genre: "Drama",
    type: "movie",
    director: "Martin Scorsese",
    maincast: "Leonardo DiCaprio, Jonah Hill, Margot Robbie",
    img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "iszwuX1AK6A",
  },
  // ============ BATCH 15: MORE TV SHOWS ============
  {
    title: "Stranger Things",
    year: "2016",
    genre: "Sci-fi",
    type: "tv",
    director: "The Duffer Brothers",
    maincast: "Millie Bobby Brown, Finn Wolfhard, Winona Ryder",
    img: "https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzZWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: true,
    link: "b9EkMc79ZSU",
  },
  {
    title: "Ted Lasso",
    year: "2020",
    genre: "Comedy",
    type: "tv",
    director: "Bill Lawrence, Jason Sudeikis",
    maincast: "Jason Sudeikis, Hannah Waddingham, Juno Temple",
    img: "https://m.media-amazon.com/images/M/MV5BMDRkMzI2YzctN2Y0Mi00ODBmLTg4MmEtNzYwNDc4OTczMjFhXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "3u7EIiohs6U",
  },
  {
    title: "The Bear",
    year: "2022",
    genre: "Drama",
    type: "tv",
    director: "Christopher Storer",
    maincast: "Jeremy Allen White, Ebon Moss-Bachrach, Ayo Edebiri",
    img: "https://m.media-amazon.com/images/M/MV5BN2E1MjI0MTEtN2M2ZC00YmNlLWJmMDYtYzQyZmY4YmQ3MTFkXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "y-cqqAJIXhs",
  },
  {
    title: "Severance",
    year: "2022",
    genre: "Sci-fi",
    type: "tv",
    director: "Dan Erickson",
    maincast: "Adam Scott, Zach Cherry, Britt Lower",
    img: "https://m.media-amazon.com/images/M/MV5BMjkwZjcwMGQtNDAzOC00YjJiLThiYTgtNWU3ZjRiZGYwZTgzXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "xEQP4VVuyrY",
  },
  {
    title: "Fargo",
    year: "2014",
    genre: "Drama",
    type: "tv",
    director: "Noah Hawley",
    maincast: "Billy Bob Thornton, Martin Freeman, Allison Tolman",
    img: "https://m.media-amazon.com/images/M/MV5BN2NiMGE1NmYtMmZkZi00M2FiLWJhN2MtYjgwMDZkZjI2YjA2XkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "gKs8DzjPDMU",
  },
  {
    title: "True Detective",
    year: "2014",
    genre: "Drama",
    type: "tv",
    director: "Nic Pizzolatto",
    maincast: "Matthew McConaughey, Woody Harrelson, Michelle Monaghan",
    img: "https://m.media-amazon.com/images/M/MV5BN2Y4NmRlMmItMzhkYy00NDk1LWFhNjQtODg3Y2M2OWZhYTU2XkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "fVQUcaO4AvE",
  },
  {
    title: "Chernobyl",
    year: "2019",
    genre: "Drama",
    type: "tv",
    director: "Craig Mazin",
    maincast: "Jared Harris, Stellan Skarsgård, Emily Watson",
    img: "https://m.media-amazon.com/images/M/MV5BNTdkN2QwMDUtZmY2Yy00YjljLTk3NTQtOGNkYzNhNjAxMjMyXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "s9APLXM9Ei8",
  },
  {
    title: "Fleabag",
    year: "2016",
    genre: "Comedy",
    type: "tv",
    director: "Phoebe Waller-Bridge",
    maincast: "Phoebe Waller-Bridge, Sian Clifford, Olivia Colman",
    img: "https://m.media-amazon.com/images/M/MV5BMjA4MzU5NzQxNV5BMl5BanBnXkFtZTgwOTg3MDA5NzM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "aX2yCmzNPFg",
  },
  {
    title: "The Good Place",
    year: "2016",
    genre: "Comedy",
    type: "tv",
    director: "Michael Schur",
    maincast: "Kristen Bell, Ted Danson, William Jackson Harper",
    img: "https://m.media-amazon.com/images/M/MV5BMTkxOTY0MzMwM15BMl5BanBnXkFtZTgwMjkwMjc5ODE@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "RfBgT5djaQw",
  },
  {
    title: "Brooklyn Nine-Nine",
    year: "2013",
    genre: "Comedy",
    type: "tv",
    director: "Dan Goor, Michael Schur",
    maincast: "Andy Samberg, Stephanie Beatriz, Terry Crews",
    img: "https://m.media-amazon.com/images/M/MV5BNzVkYWY4NzYtMWFlZi00YzkwLThhZDItZjcxYTU4ZTMzMDZmXkEyXkFqcGdeQXVyODUxOTU0OTg@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "sEOuJ4z5aTc",
  },
  // ============ BATCH 16: MORE ANIMATED MOVIES ============
  {
    title: "Spider-Man: Into the Spider-Verse",
    year: "2018",
    genre: "Animated",
    type: "movie",
    director: "Bob Persichetti, Peter Ramsey",
    maincast: "Shameik Moore, Jake Johnson, Hailee Steinfeld",
    img: "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: true,
    link: "g4Hbz2jLxvQ",
  },
  {
    title: "Spider-Man: Across the Spider-Verse",
    year: "2023",
    genre: "Animated",
    type: "movie",
    director: "Joaquim Dos Santos, Kemp Powers",
    maincast: "Shameik Moore, Hailee Steinfeld, Oscar Isaac",
    img: "https://m.media-amazon.com/images/M/MV5BMzI0NmVkMjEtYmY4MS00ZDMxLTlkZmEtMzU4MDQxYTMzMjU2XkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "cqGjhVJWtEg",
  },
  {
    title: "Encanto",
    year: "2021",
    genre: "Animated",
    type: "movie",
    director: "Byron Howard, Jared Bush",
    maincast: "Stephanie Beatriz, María Cecilia Botero, John Leguizamo",
    img: "https://m.media-amazon.com/images/M/MV5BNjE5NzA4ZDctOTJkZi00NjM0LWJhZGYtOGQ2ZTZhNGNlMTAxXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "CaimKeDcudo",
  },
  {
    title: "Soul",
    year: "2020",
    genre: "Animated",
    type: "movie",
    director: "Pete Docter, Kemp Powers",
    maincast: "Jamie Foxx, Tina Fey, Graham Norton",
    img: "https://m.media-amazon.com/images/M/MV5BZGE1MDg5M2MtNTkyZS00MTY5LTg1YzUtZTlhZmM1Y2EwNmFmXkEyXkFqcGdeQXVyNjA3OTI0MDc@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "xOsLIiBStEs",
  },
  {
    title: "Luca",
    year: "2021",
    genre: "Animated",
    type: "movie",
    director: "Enrico Casarosa",
    maincast: "Jacob Tremblay, Jack Dylan Grazer, Emma Berman",
    img: "https://m.media-amazon.com/images/M/MV5BZTQyNTU0MDktYTFkYi00ZjNhLWE2ODctMzBkM2U1ZTliNTZiXkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "mYfJxlgR2jw",
  },
  {
    title: "Turning Red",
    year: "2022",
    genre: "Animated",
    type: "movie",
    director: "Domee Shi",
    maincast: "Rosalie Chiang, Sandra Oh, Ava Morse",
    img: "https://m.media-amazon.com/images/M/MV5BNjY0MGEzZmQtZWMxNi00MWVhLWJlMTUtMmU5MzAwNmVlMGZiXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "XdKzUbAiswE",
  },
  {
    title: "Moana",
    year: "2016",
    genre: "Animated",
    type: "movie",
    director: "Ron Clements, John Musker",
    maincast: "Auli'i Cravalho, Dwayne Johnson, Rachel House",
    img: "https://m.media-amazon.com/images/M/MV5BMjI4MzU5NTExNF5BMl5BanBnXkFtZTgwNzY1MTEwMDI@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "LKFuXETZUsI",
  },
  {
    title: "Big Hero 6",
    year: "2014",
    genre: "Animated",
    type: "movie",
    director: "Don Hall, Chris Williams",
    maincast: "Scott Adsit, Ryan Potter, Daniel Henney",
    img: "https://m.media-amazon.com/images/M/MV5BMDliOTIzNmUtOTllOC00NDU3LWFiNjYtMGM0NDc1YTMxNjYxXkEyXkFqcGdeQXVyNTM3NzExMDQ@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "z3biFxZIJOQ",
  },
  {
    title: "Tangled",
    year: "2010",
    genre: "Animated",
    type: "movie",
    director: "Nathan Greno, Byron Howard",
    maincast: "Mandy Moore, Zachary Levi, Donna Murphy",
    img: "https://m.media-amazon.com/images/M/MV5BMTAxNDYxMjg0MjNeQTJeQWpwZ15BbWU3MDcyNTk2OTM@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "f0S_dNzuFJg",
  },
  {
    title: "Brave",
    year: "2012",
    genre: "Animated",
    type: "movie",
    director: "Mark Andrews, Brenda Chapman",
    maincast: "Kelly Macdonald, Billy Connolly, Emma Thompson",
    img: "https://m.media-amazon.com/images/M/MV5BMzgwODk3ODA1NF5BMl5BanBnXkFtZTcwNjU3NjQ0Nw@@._V1_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "TEHWDA_6e3M",
  },
];
