export const movie = [
  {
    title: "Scarface",
    year: "1983",
    genre: "Action",
    type: "movie",
    director: "Brian De Palma",
    maincast: "Al Pacino",
    img: "https://m.media-amazon.com/images/M/MV5BYTBjNDBhZWUtZjg1MS00NzhjLWJlNWUtM2E0ZjcwZGExYzY3XkEyXkFqcGdeQXVyMjMzMDI4MjQ@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: false,
    link: "cv276Wg3e7I",
  },
  {
    title: "Breaking Bad",
    year: "2008",
    genre: "Drama",
    type: "tv",
    director: "Vince Gilligan",
    maincast: "Bryan Cranston,Anna Gunn,Aaron Paul",
    img: "https://m.media-amazon.com/images/M/MV5BMTJiMzgwZTktYzZhZC00YzhhLWEzZDUtMGM2NTE4MzQ4NGFmXkEyXkFqcGdeQWpybA@@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: false,
    link: "HhesaQXLuRY",
  },
  {
    title: "Avatar",
    year: "2009",
    genre: "Sci-Fi",
    type: "movie",
    director: "James Cameron",
    maincast: "Sam Worthington,Zoe Saldana",
    img: "https://m.media-amazon.com/images/M/MV5BMTMxOTEwNDcxN15BMl5BanBnXkFtZTcwOTg0MTUzNA@@._V1_.jpg",
    rating: 4.5,
    isFeatured: true,
    isTrending: false,
    link: "5PSNL1qE6VY",
  },
  {
    title: "Spiderman",
    year: "2002",
    genre: "Action",
    type: "movie",
    director: "Sam Raimi",
    maincast: "Tobey Maguire,Kirsten Dunst",
    img: "https://occ-0-32-988.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABZrkp8RvUrZVjc9GYn8-jlxnEa66xgTexL7oinRF0s2MtkbCV5CsuuRlR48sqMP0twyY46ToqL__Y3uflZ_Ln0DgZrqy6cfKas87.jpg?r=f3d",
    rating: 4,
    isFeatured: true,
    isTrending: false,
    link: "TYMMOjBUPMM",
  },
  {
    title: "The Matrix",
    year: "1999",
    genre: "Sci-Fi",
    type: "movie",
    director: "Lana Wachowski,Lilly Wachowski",
    maincast: "Keanu Reaves",
    img: "https://m.media-amazon.com/images/M/MV5BZGMzZDc3ZGUtMDIzYy00Y2ViLWE3ZGYtNDg2ZWM0YjBiMTk2XkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "nUEQNVV3Gfs",
  },
  {
    title: "Black Panther:Wakanda Forever",
    year: "2022",
    genre: "Sci-Fi",
    type: "movie",
    director: "Ryan Coogler",
    maincast: "Letitia Wright",
    img: "https://m.media-amazon.com/images/M/MV5BNTM4NjIxNmEtYWE5NS00NDczLTkyNWQtYThhNmQyZGQzMjM0XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: true,
    link: "_Z3QKkl1WyM",
  },
  {
    title: "The Godfather",
    year: "1972",
    genre: "Action",
    type: "movie",
    director: "Francis Ford Coppola",
    maincast: "Marlon Brando",
    img: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "UaVTIH8mujA",
  },
  {
    title: "Iron Man",
    year: "2008",
    genre: "Action",
    type: "movie",
    director: "Jon Favreau",
    maincast: "Robert Downey Jr,Gwyneth Paltrow,Terrence Howard",
    img: "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_FMjpg_UX1000_.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: false,
    link: "8ugaeA-nMTc",
  },
  {
    title: "SPIDER-MAN: NO WAY HOME",
    year: "2021",
    genre: "Sci-Fi",
    type: "movie",
    director: "Jon Watts",
    maincast: "Tom Holland,Zendaya",
    img: "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UX1000_.jpg",
    rating: 4,
    isFeatured: false,
    isTrending: false,
    link: "rt-2cxAiPJk",
  },
  {
    title: "VENOM",
    year: "2018",
    genre: "Sci-Fi",
    type: "movie",
    director: "Ruben Fleischer",
    maincast: "Tom Hardy",
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTvGNXRmC76GfZrgM7P_oY0nZqg00bsjC7E5zu4dZBReXiHD_kt",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "u9Mv98Gr5pY",
  },
  {
    title: "POKÉMON Detective Pikachu",
    year: "2019",
    genre: "Sci-Fi",
    type: "movie",
    director: "Rob Letterman",
    maincast: "Ryan Reynolds",
    img: "https://m.media-amazon.com/images/M/MV5BMDkxNzRmNDYtMDY0OS00N2JhLTkzZWUtMWE3MzZkNDk1MmJiXkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_FMjpg_UX1000_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "1roy4o4tqQM",
  },
  {
    title: "IT",
    year: "2017",
    genre: "Horror",
    type: "movie",
    director: "Andy Muschietti",
    maincast: "	Jaeden Lieberher",
    img: "https://upload.wikimedia.org/wikipedia/en/5/5a/It_%282017%29_poster.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "FnCdOQsX5kc",
  },
  {
    title: "Toy Story 4",
    year: "2019",
    genre: "Animated",
    type: "movie",
    director: "Josh Cooley",
    maincast: "Tom Hanks",
    img: "https://upload.wikimedia.org/wikipedia/en/4/4c/Toy_Story_4_poster.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: true,
    link: "wmiIUN-7qhE",
  },
  {
    title: "The Nun",
    year: "2018",
    genre: "Horror",
    type: "movie",
    director: "Corin Hardy",
    maincast: "Bonnie Aarons,Charlotte Hope",
    img: "https://m.media-amazon.com/images/M/MV5BMjM3NzQ5NDcxOF5BMl5BanBnXkFtZTgwNzM4MTQ5NTM@._V1_.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "KukngjCoN-s",
  },
  {
    title: "IT CHAPTER TWO",
    year: "2019",
    genre: "Horror",
    type: "movie",
    director: "Andrés Muschietti",
    maincast: "Jessica Chastain",
    img: "https://m.media-amazon.com/images/M/MV5BYTJlNjlkZTktNjEwOS00NzI5LTlkNDAtZmEwZDFmYmM2MjU2XkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_.jpg",
    rating: 3,
    isFeatured: false,
    isTrending: false,
    link: "zqUopiAYdRg",
  },
  {
    title: "Avengers: Infinity War",
    year: "2017",
    genre: "Sci-Fi",
    type: "movie",
    director: "Anthony and Joe Russo",
    maincast:
      "Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo,Chris Evans,Scarlett Johansson",
    img: "https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg",
    rating: 4.5,
    isFeatured: false,
    isTrending: true,
    link: "6ZfuNTqbHE8",
  },
  {
    title: "Incredibles 2",
    year: "2018",
    genre: "Animated",
    type: "movie",
    director: "Brad Bird",
    maincast: "Craig T. Nelson",
    img: "https://upload.wikimedia.org/wikipedia/en/1/1f/Incredibles_2_%282018_animated_film%29.jpg",
    rating: 3.5,
    isFeatured: false,
    isTrending: false,
    link: "i5qOzqD9Rms",
  },
];

// {
//     title: "",
//     year: "",
//     genre: "",
//     type: "movie",
//     director: "",
//     maincast: "",
//     img: "",
//     rating: 4,
//     isFeatured: false,
//     isTrending: false,
//   },
